"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "zh" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  zh: {
    // Navigation
    "nav.home": "首页",
    "nav.test": "测试",
    "nav.checkin": "打卡",
    "nav.leaderboard": "排行榜",
    "nav.plans": "戒色方案",
    "nav.pricing": "定价",
    "nav.profile": "我的",
    "nav.signin": "Log in",
    "nav.signup": "注册",
    "nav.signout": "登出",

    // Hero section
    "hero.title": "戒色是你唯一选择",
    "hero.subtitle":
      "告别色欲沉溺，掌控你的身体与意志。\n通过科学测试、连续打卡、行为追踪，\nAwaken 帮助你一点一滴重建专注、力量与自信。",
    "hero.start_test": "开始测试",
    "hero.register": "立即注册",

    // Stats
    "stats.users": "用户选择我们",
    "stats.streak": "平均连续天数",
    "stats.success": "成功率",

    // Features
    "features.title": "核心功能",
    "features.subtitle": "我们提供全方位的戒色支持工具，帮助您建立健康的生活方式",
    "features.test.title": "专业测试",
    "features.test.desc": "科学评估色瘾程度，了解自己的真实状况",
    "features.checkin.title": "每日打卡",
    "features.checkin.desc": "记录每日状态，培养良好习惯",
    "features.leaderboard.title": "排行榜",
    "features.leaderboard.desc": "与其他用户一起进步，互相激励",
    "features.community.title": "社区支持",
    "features.community.desc": "加入成长社区，获得专业指导",

    // Benefits
    "benefits.title": "戒色带来的\n积极改变",
    "benefits.subtitle": "科学研究表明，戒除色瘾能够显著改善身心健康，提升生活质量。",
    "benefits.focus": "提升专注力和精神状态",
    "benefits.relationships": "改善人际关系质量",
    "benefits.willpower": "增强自控力和意志力",
    "benefits.sleep": "获得更好的睡眠质量",
    "benefits.efficiency": "提高工作和学习效率",
    "benefits.lifestyle": "建立健康的生活方式",

    // CTA
    "cta.title": "准备好开始你的成长之旅了吗？",
    "cta.subtitle": "加入我们的社区，与数万名用户一起，重新掌控自己的人生，迎接更美好的未来。",
    "cta.test": "免费测试",
    "cta.register": "立即注册",

    // === 新增首页相关 ===
    "home.awaken_title": "Awaken 戒色助手",
    "home.awaken_subtitle": "Awaken your willpower. Track your journey with wisdom from Eastern traditions.",
    "home.awaken_slogan": "✨ 30天助你清除色瘾，信任与坚持定将逆转命运！ ✨",
    "home.start_test_button": "开启用户测试",
    "home.world_first": "世界上第一个支持免费视频打卡的",
    "home.buddhist": "佛学",
    "home.nofap_site": "戒色网站",
    "home.traditional_method": "经过数百万戒色实战总结的中华传统文化戒色方法",
    "home.copyright": "© 2025 • Awaken 戒色助手 保留所有权利。",
    "home.features_title": "Awaken 的主要特点",
    "home.features_subtitle": "科学的方法，贴心的陪伴，助您重获新生",
    "home.feature_daily_checkin_title": "每日打卡",
    "home.feature_daily_checkin_desc": "状态、日志、视频打卡三位一体，坚持每日打卡，记录您的进步历程，建立良好习惯",
    "home.feature_test_title": "科学测试",
    "home.feature_test_desc": "通过专业的色瘾测试评估，了解自己的成瘾程度，为制定个性化戒色方案提供科学依据",
    "home.feature_plans_title": "戒色方案",
    "home.feature_plans_desc": "结合科学色瘾测试，制定专属会员计划，30天大幅降低色欲，循序渐进，2个月彻底戒色，1年身体筑基，重回巅峰状态",
    "home.feature_leaderboard_title": "排行榜",
    "home.feature_leaderboard_desc": "全网展示戒色英雄榜前十位，争做连续守戒的戒色英雄吧，与志同道合的朋友一起努力，互相激励成长",
    "home.about_desc": "Awaken: 由科学测试驱动的戒色平台，助力用户重获新生。",

    // === 新增首页标签相关 ===
    "home.tag_video_checkin": "视频打卡",
    "home.tag_free_use": "免费使用",
    "home.tag_buddhist": "佛学断念",
    "home.tag_gpt": "GPT-3.5 Turbo",

    // === 新增隐私政策相关 ===
    "privacy.title": "隐私政策",
    "privacy.collection.title": "信息收集",
    "privacy.collection.desc": "我们仅收集您主动提供的必要信息，包括邮箱地址、用户名等基本信息，用于账户创建和服务提供。",
    "privacy.usage.title": "信息使用",
    "privacy.usage.desc": "您的个人信息仅用于：提供戒色助手服务、记录打卡进度、生成个性化建议、发送重要通知。",
    "privacy.protection.title": "信息保护",
    "privacy.protection.desc": "我们采用行业标准的安全措施保护您的数据，包括加密存储、安全传输等技术手段。",
    "privacy.third_party.title": "第三方服务",
    "privacy.third_party.desc": "我们使用Google、GitHub等第三方登录服务，这些服务有各自的隐私政策。我们不会向第三方出售您的个人信息。",
    "privacy.deletion.title": "数据删除",
    "privacy.deletion.desc": "您可以随时联系我们删除您的账户和相关数据。删除后，您的个人信息将从我们的系统中永久移除。",
    "privacy.contact.title": "联系我们",
    "privacy.contact.desc": "如果您对隐私政策有任何疑问，请通过平台内的反馈功能联系我们。",
    "privacy.last_updated": "最后更新：2025年1月",

    // === 新增AI助教相关 ===
    "ai.title": "AI戒色助教",
    "ai.unlimited": "无限制对话",
    "ai.remaining_today": "今日剩余",
    "ai.premium": "会员",
    "ai.free": "免费",
    "ai.today_messages": "今日消息",
    "ai.unlimited_use": "无限制使用",
    "ai.remaining": "剩余",
    "ai.messages": "条",
    "ai.quick_replies_title": "快速提问",

    // === 新增AI助教快速提问相关 ===
    "ai.quick_reply_urges": "如何应对戒色欲望？",
    "ai.quick_reply_insomnia": "戒色期间失眠怎么办？",
    "ai.quick_reply_habits": "如何建立健康的习惯？",
    "ai.quick_reply_recovery": "戒色后身体恢复情况",
    "ai.quick_reply_relapse": "如何避免复发？",

    // === 新增测试结果概览相关 ===
    "home.test_overview_title": "测试结果概览",
    "home.retest_button": "重新测试",
    "home.test_score": "测试得分",
    "home.dependency_level": "依赖等级",
    "home.daily_tasks": "每日任务",
    "home.start_exclusive_plan": "开始属于你的专属今日计划吧",
    "home.enter_nofap_plan": "进入戒色方案",
    "home.join_premium_suggestion": "建议加入专属会员计划，戒色30天即可见效",
    "home.learn_membership_details": "了解会员详情",

    // === 新增每日推送相关 ===
    "daily_push.title": "今日专属推送",
    "daily_push.member_exclusive": "会员专享",
    "daily_push.unlock_title": "解锁每日专属推送",
    "daily_push.unlock_desc": "成为会员，每天获取精选的戒色语录、成长建议和心灵鸡汤",
    "daily_push.preview_quote": "真正的成长不是战胜别人，而是超越昨天的自己。",
    "daily_push.preview_label": "— 会员专属内容预览",
    "daily_push.footer": "每日更新 · 专属内容",

    // === 新增底部导航相关 ===
    "footer.about": "关于",
    "footer.features": "特点",
    "footer.pricing": "定价",
    "footer.tools": "工具",
    "footer.test": "色瘾测试",
    "footer.checkin": "每日打卡",

    // === 新增方案页相关 ===
    "plans.emergency_button": "紧急情况！点我自救",
    "plans.emergency.cold_water": "冷水冲击",
    "plans.emergency.cold_water_cmd": "立刻去洗冷水澡！用冷水冲头和脸，直到你感到彻底清醒。",
    "plans.emergency.cold_water_reason": "冷水刺激能迅速打断大脑的冲动回路，让你恢复理智。",
    "plans.emergency.breathing": "深呼吸30次",
    "plans.emergency.breathing_cmd": "现在，深呼吸30次。每一次都要慢慢吸气、慢慢呼气。",
    "plans.emergency.breathing_reason": "深呼吸能让你的身体和大脑迅速冷静下来，降低生理冲动。",
    "plans.emergency.pepper": "辣椒刺激",
    "plans.emergency.pepper_cmd": "如果家里有爆辣的辣椒，马上吃一个，让身体感受到强烈刺激。",
    "plans.emergency.pepper_reason": "强烈的味觉刺激能转移你的注意力，打断欲望循环。",
    "plans.emergency.environment": "环境切换",
    "plans.emergency.environment_cmd": "立刻离开房间，去户外人多的地方，哪怕只是楼下小区，直到冲动消退。",
    "plans.emergency.environment_reason": "换个环境、见到人群，大脑会自动切换到社交和理性模式。",
    "plans.emergency.mantra": "精神转移",
    "plans.emergency.mantra_cmd": "现在，读准提神咒7遍，或大声背诵你最喜欢的励志语录。",
    "plans.emergency.mantra_reason": "用正向的声音和信念，彻底清空脑中的杂念。",
    "plans.level.mild": "轻度依赖",
    "plans.level.moderate": "中度依赖",
    "plans.level.severe": "重度依赖",
    "plans.overview_title": "测试结果概览",
    "plans.retest": "重新测试",
    "plans.test_score": "测试得分",
    "plans.addiction_level": "依赖等级",
    "plans.daily_tasks": "每日任务",
    "plans.current_streak": "当前连续天数",
    "plans.current_level": "当前等级",
    "plans.todays_progress": "今日进度",
    "plans.free_tasks": "免费任务",
    "plans.addiction_plan": "依赖方案",
    "plans.premium_tasks": "会员专享任务",
    "plans.advanced_tasks": "个高级任务",
    "plans.premium_exclusive_tasks": "会员专享任务",

    // === 新增任务相关 ===
    "task.daily_checkin": "每日打卡",
    "task.daily_checkin_desc": "记录今日状态",
    "task.journal": "戒色日志",
    "task.journal_desc": "记录今日感悟",
    "task.video_checkin": "视频打卡",
    "task.video_checkin_desc": "录制视频分享",
    "task.audio_listen": "听戒色录音（第1-{count}集）",
    "task.audio_desc": "聆听戒色音频{count}集，提升意志力",
    "task.article_read": "读戒色文章（第1-{count}章）",
    "task.article_desc": "阅读戒色文章{count}章，增长智慧",
    "task.mantra_chant": "念诵准提神咒{count}遍",
    "task.mantra_desc": "净化心灵，增强定力，今日目标{count}遍",
    "task.meditation": "冥想10-20分钟",
    "task.meditation_desc": "静心修行，感恩冥想，平复欲望",
    "task.meditation_instruction": "找一个安静整洁的地方，盘腿而坐，闭上眼睛，专注呼吸，脑海中回想生活中值得感恩的人和事，让内心充满温暖和力量。每次建议10-20分钟。",
    "task.sleep": "吉祥卧（还阳卧）",
    "task.sleep_desc": "仰卧床上，双手放腰后，双脚合十，感受体内暖流",
    "task.sleep_instruction": "仰卧在床，双手自然放于腰后，双脚合十，闭上眼睛，感受一股温暖的气流在体内流动，身体会很快热起来。这是中华传统的还阳卧法，有助于恢复精力、平复欲望。",
    // === 新增有氧运动相关 ===
    "task.exercise": "有氧运动10分钟",
    "task.exercise_desc": "增强体质，吸收自然能量",
    "task.exercise_instruction": "进行10分钟有氧运动，如跑步、跳绳、快走等，提高心率，增强体质。推荐在公园晨跑，拥抱大树等户外活动，吸收自然能量。",

    // === 新增AI助教相关 ===
    "ai.welcome": "您好！我是您的AI戒色助教，专门为您提供戒色指导和支持。我可以帮助您：\n\n• 解答戒色相关问题\n• 提供心理支持和建议\n• 分享戒色技巧和方法\n• 分析您的戒色进度\n\n有什么可以帮助您的吗？",
    "ai.input_placeholder": "输入您的问题...",
    "ai.input_placeholder_free": "输入您的问题... (免费用户每日5条)",
    "ai.upgrade_tip": "升级会员享受无限制AI助教服务",
    "ai.limit_reached": "您已达到今日免费消息限制（5条）。升级会员可享受无限制AI助教服务！",

    // === 新增公告栏相关 ===
    "announcement.motd": "🎉 当前为 MVP 内测版本，所有功能暂时免费使用 ✨ 我们将在正式上线后推出会员机制，解锁更多专属功能 💎\n            欢迎广大戒友使用体验，在首页下方的意见栏反馈您的宝贵建议 💬\n            您的意见是我们优化网站的宝贵动力，希望正式版早日与您相见，助力戒色成功！🚀 感谢您的支持与陪伴 ❤️",

    // === 新增设置页相关 ===
    "setup.title": "系统设置",
    "setup.create_bucket": "创建头像存储桶",
    "setup.created": "已创建",
    "setup.not_created": "未创建",
    "setup.creating": "创建中...",
    "setup.desc": "此页面用于执行系统设置任务，如创建必要的存储桶。\n完成设置后，您可以返回应用程序继续使用。",

    // === 新增引导页相关 ===
    "intro.welcome": "欢迎来到Awaken",
    "intro.start_journey": "开始您的<strong>重生之旅</strong><br/>重新掌控自己的人生<br/><small>基于科学研究的戒色康复方法</small>",
    "intro.truth": "认识真相",
    "intro.porn_harm": "色情内容正在<strong>悄悄伤害</strong>您的大脑<br/>影响专注力、记忆力和决策能力<br/><small>神经科学研究：长期观看会降低大脑灰质密度</small>",
    "intro.damage": "身心受损",
    "intro.anxiety_depression": "长期观看会导致<strong>焦虑抑郁</strong><br/>影响人际关系和自信心<br/><small>心理学研究显示：与社交焦虑症状密切相关</small>",

    // === 新增反馈相关 ===
    "feedback.title": "用户反馈",
    "feedback.subtitle": "您的意见对我们很重要",
    "feedback.email_label": "邮箱地址（可选）",
    "feedback.email_placeholder": "your@email.com",
    "feedback.feedback_label": "您的建议或反馈",
    "feedback.feedback_placeholder": "请分享您的使用体验、建议或遇到的问题...",
    "feedback.rating_label": "整体评分",
    "feedback.submit": "提交反馈",
    "feedback.submitting": "提交中...",
    "feedback.success_title": "感谢您的反馈",
    "feedback.success_message": "我们已收到您的意见，将认真考虑并持续改进。",
    "feedback.submit_another": "提交其他反馈",

    // === 新增定价页相关 ===
    "pricing.title": "定价与会员方案",
    "pricing.subtitle": "选择适合你的戒色成长方案，免费体验或升级会员解锁全部功能。",
    "pricing.free_plan": "免费版",
    "pricing.premium_plan": "会员版",
    "pricing.free_desc": "基础功能永久免费使用，适合新手体验。",
    "pricing.premium_desc": "解锁全部专属功能，获得个性化指导与深度成长。",
    "pricing.forever": "永久免费",
    "pricing.recommended": "推荐",
    "pricing.per_month": "/月",
    "pricing.continuous_update": "持续更新更多会员专属内容",
    "pricing.payment_error": "支付出错，请重试或联系客服。",
    "pricing.payment_success": "支付成功后自动开通会员。",
    "pricing.member_access": "会员可立即访问全部专属内容。",
    "pricing.cancel_info": "会员可随时取消，7天无理由退款保障。",
    "pricing.contact_support": "如有疑问请联系客服。",
    "pricing.free_trial": "免费体验",
    "pricing.join_membership": "加入会员",
    "pricing.benefit.free.status": "免费状态打卡",
    "pricing.benefit.free.journal": "免费日志记录",
    "pricing.benefit.free.video": "每月3次免费视频打卡",
    "pricing.benefit.free.ai": "每月5次AI助教",
    "pricing.benefit.premium.all_free": "包含免费版所有权益",
    "pricing.benefit.premium.daily_push": "每日会员专属推送",
    "pricing.benefit.premium.video": "无限次视频打卡",
    "pricing.benefit.premium.ai": "无限次AI助教",
    "pricing.benefit.premium.plan": "个性化戒色计划",
    "pricing.benefit.premium.analytics": "高级数据分析",

    // === 新增打卡页面相关 ===
    "checkin.title": "每日打卡",
    "checkin.subtitle": "记录你的戒色之路，每一天都很重要",
    "checkin.loading": "加载中...",
    "checkin.pleaseLogin": "请先登录",
    "checkin.currentStreak": "当前连续\n守戒天数",
    "checkin.currentConsecutive": "当前连续",
    "checkin.maxStreak": "历史最大\n连续天数",
    "checkin.historicalBest": "历史最佳",
    "checkin.successRate": "成功率",
    "checkin.basedOnStreak": "基于连续天数",
    "checkin.totalDays": "总打卡天数",
    "checkin.accumulatedRecord": "累计记录",

    // === 新增打卡模态框相关 ===
    "checkinModal.checkin": "打卡",
    "checkinModal.reset": "重新填写",
    "checkinModal.statusAndLog": "状态 & 日志",
    "checkinModal.video": "视频",
    "checkinModal.todayStatus": "今日状态",
    "checkinModal.success": "今天守戒成功！",
    "checkinModal.failed": "今天破戒了！",
    "checkinModal.todayReflection": "今日感悟 (可选)",
    "checkinModal.reflectionPlaceholder": "记录今天的心情、感悟或遇到的挑战...",
    "checkinModal.videoRecord": "视频记录 (可选)",
    "checkinModal.videoUploaded": "视频已上传",
    "checkinModal.reRecord": "重新录制",
    "checkinModal.saveCheckin": "保存打卡",
    "checkinModal.saving": "保存中...",
    "checkinModal.uploading": "上传中...",
    "checkinModal.resetting": "重置中...",
    "checkinModal.userNotLoggedIn": "用户未登录，请重新登录",
    "checkinModal.saveFailed": "保存失败",
    "checkinModal.resetFailed": "重置失败",
    "checkinModal.videoUploadSuccess": "视频上传成功！",
    "checkinModal.existingRecordCleared": "已清除现有记录，可以重新填写",
    "checkin.saveSuccess": "打卡保存成功！",

    // === 新增通用提示相关 ===
    "common.loadFailed": "加载失败",
    "common.saveFailed": "保存失败",
    "common.animationLoadFailed": "动画加载失败",
    "common.userVerificationFailed": "用户验证失败，请重新登录",
    "common.loadDataFailed": "加载数据失败",
    "common.resetFailed": "重置失败",

    // === 新增日历组件相关 ===
    "calendar.months.1": "一月",
    "calendar.months.2": "二月", 
    "calendar.months.3": "三月",
    "calendar.months.4": "四月",
    "calendar.months.5": "五月",
    "calendar.months.6": "六月",
    "calendar.months.7": "七月",
    "calendar.months.8": "八月",
    "calendar.months.9": "九月",
    "calendar.months.10": "十月",
    "calendar.months.11": "十一月",
    "calendar.months.12": "十二月",
    "calendar.weekdays.0": "日",
    "calendar.weekdays.1": "一",
    "calendar.weekdays.2": "二",
    "calendar.weekdays.3": "三",
    "calendar.weekdays.4": "四",
    "calendar.weekdays.5": "五",
    "calendar.weekdays.6": "六",

    // === 新增日历详细内容相关 ===
    "calendar.year": "",
    "calendar.today": "今",
    "calendar.makeup": "补",
    "calendar.todayTooltip": "今天可以正常操作",
    "calendar.legend.today": "今天",
    "calendar.legend.success": "守戒",
    "calendar.legend.failed": "破戒",
    "calendar.legend.makeup": "可补打卡",
    "calendar.legend.journal": "日志",
    "calendar.legend.video": "视频",
    "calendar.rules.today": "今天可以正常打卡和修改",
    "calendar.rules.recent": "过去3天内可以补打卡",
    "calendar.rules.old": "超过3天的记录只能查看",
    "calendar.rules.future": "未来日期无法操作",
    // === 新增日历权限 reason 相关 ===
    "calendar.reason.makeup": "可以补打卡",
    "calendar.reason.today": "今天可以正常操作",
    "calendar.reason.future": "未来日期无法操作",
    "calendar.reason.old_with_data": "只能查看历史记录",
    "calendar.reason.old_no_data": "超过补打卡时限",
    "calendar.reason.unknown": "无法操作",

    // === 新增排行榜页面相关 ===
    "leaderboard.title": "守戒排行榜",
    "leaderboard.subtitle": "坚持守戒，成就更好的自己",
    "leaderboard.me": "我",
    "leaderboard.myRank": "我的排名: {rank}",
    "leaderboard.currentStreak": "当前连续守戒天数",
    "leaderboard.days": "天",
    "leaderboard.user": "用户",
    "leaderboard.anonymous": "匿名用户",
    "leaderboard.hero": "守戒勇士",
    "leaderboard.currentStreakShort": "当前连续天数",
    "leaderboard.noData": "暂无排行榜数据",
    "leaderboard.beFirst": "成为第一个上榜的勇士吧！",

    // === 新增 plans 戒色方案页面相关 ===
    "plans.title": "戒色方案",
    "plans.stage1": "初期适应",
    "plans.stage1_days": "1-20天",
    "plans.stage2": "稳定发展",
    "plans.stage2_days": "21-59天",
    "plans.stage3": "深度转化",
    "plans.stage3_days": "60-179天",
    "plans.stage4": "巩固期",
    "plans.stage4_days": "180天+",
    "plans.emergency.cold_water": "冷水冲击",
    "plans.emergency.cold_water_cmd": "立刻去洗冷水澡！用冷水冲头和脸，直到你感到彻底清醒。",
    "plans.emergency.cold_water_reason": "冷水刺激能迅速打断大脑的冲动回路，让你恢复理智。",
    "plans.emergency.breathing": "深呼吸30次",
    "plans.emergency.breathing_cmd": "现在，深呼吸30次。每一次都要慢慢吸气、慢慢呼气。",
    "plans.emergency.breathing_reason": "深呼吸能让你的身体和大脑迅速冷静下来，降低生理冲动。",
    "plans.emergency.pepper": "辣椒刺激",
    "plans.emergency.pepper_cmd": "如果家里有爆辣的辣椒，马上吃一个，让身体感受到强烈刺激。",
    "plans.emergency.pepper_reason": "强烈的味觉刺激能转移你的注意力，打断欲望循环。",
    "plans.emergency.environment": "环境切换",
    "plans.emergency.environment_cmd": "立刻离开房间，去户外人多的地方，哪怕只是楼下小区，直到冲动消退。",
    "plans.emergency.environment_reason": "换个环境、见到人群，大脑会自动切换到社交和理性模式。",
    "plans.emergency.mantra": "精神转移",
    "plans.emergency.mantra_cmd": "现在，读准提神咒7遍，或大声背诵你最喜欢的励志语录。",
    "plans.emergency.mantra_reason": "用正向的声音和信念，彻底清空脑中的杂念。",
    "plans.unlock_full": "解锁完整戒色方案",
    "plans.unlock_desc": "升级会员获得{count}个高级任务，包括专业音频、文章阅读、视频打卡等",
    "plans.upgrade_now": "立即升级",
    "plans.audio.lesson1": "戒色音频 - 第1课",
    "plans.audio.lesson2": "戒色音频 - 第2课",
    "plans.audio.lesson3": "戒色音频 - 第3课",
    "plans.article.chapter1": "引言+第一章",
    "plans.article.chapter2": "第二章",
    "plans.article.chapter3": "第三章",
    "plans.article.chapter4": "第四章",
    "plans.article.chapter5": "第五章",
    "plans.article.chapter6": "第六章",
    "plans.article.title": "重返光明 - 戒色指南",
    "plans.article.desc": "专业的戒色指导手册，包含科学方法和实践技巧",
    "plans.mantra.title": "准提神咒",
    "plans.mantra.desc": "准提神咒，净化心灵，增强意志力",
    "plans.mantra.note": "这是带拼音的准提神咒图片。跟随汉字和拼音一起念诵，即使不懂中文，也请专注于声音和意念。坚持念诵有助于净化心灵、增强意志力。",
    "plans.level.mild": "轻度依赖",
    "plans.level.moderate": "中度依赖",
    "plans.level.severe": "重度依赖",


    "plans.premium_features": "会员专享功能",
    "plans.personalized_guidance": "个性化指导",
    "plans.customized_plan": "基于测试结果的定制化戒色方案",
    "plans.ai_analysis": "AI智能分析和建议",
    "plans.online_counseling": "专业心理咨询师在线指导",
    "plans.progress_tracking": "个人进度跟踪和分析报告",
    "plans.advanced_tools": "高级工具",
    "plans.meditation_audio": "冥想音频库（50+专业音频）",
    "plans.nofap_books": "戒色电子书籍（20+本专业书籍）",
    "plans.emergency_help": "紧急求助功能",
    "plans.community_vip": "社区VIP专区交流",
    "plans.upgrade_to_premium": "升级会员解锁全部功能",
    "plans.upgrade_to_premium_title": "升级会员解锁高级功能",
    "plans.premium_exclusive_features": "会员专享功能",
    "plans.professional_nofap_audio": "专业戒色音频指导",
    "plans.nofap_knowledge_article": "戒色知识文章库",
    "plans.video_checkin": "视频打卡功能",
    "plans.personalized_nofap_plan": "个性化戒色方案",
    "plans.maybe_later": "稍后再说",
    "plans.nofap_audio_library": "戒色音频库",
    "plans.click_to_play": "点击播放",
    "plans.playing": "正在播放",
    "plans.professional_nofap_audio_desc": "专业的戒色音频指导，帮助您建立正确的认知和习惯。建议每天聆听一节课，循序渐进地改变。",
    "plans.nofap_article_library": "戒色文章库",
    "plans.mantra_practice": "咒语修行",
    "plans.zhunti_mantra_image": "准提神咒图片",
    "plans.chanting_method": "念诵方法",
    "plans.find_quiet_place": "找一个安静的地方，保持身心清净",
    "plans.fold_hands": "双手合十，专注念诵咒语",
    "plans.chant_7_or_21_times": "每次念诵7遍或21遍",
    "plans.chant_while_visualizing_master_zhunti_compassionate_light": "念诵时观想准提菩萨的慈悲光芒",
    "plans.pray_for_mind_purification_and_willpower_strengthening": "祈求净化心灵，增强意志力",
    "plans.devote_yourself_to_chanting_zhunti_mantra_with_sincerity": "虔诚念诵准提神咒，可以净化心灵，增强意志力，帮助戒除不良习惯。",
    "plans.it_is_recommended_to_chant_once_in_the_morning_and_once_in_the_evening_every_day": "建议每天早晚各念诵一次，",
    "plans.with_perseverance": "持之以恒。",
    "plans.mark_as_completed": "完成念诵",
    "plans.task_instructions": "任务指导",
    "plans.i_understand": "我知道了",
    "plans.emergency_self_help": "紧急自救",
    "plans.end": "结束",
    "plans.completed_next_step": "已完成，下一步",
    "plans.cannot_skip_step": "每一步都不能跳过，坚持做完！",
    "plans.successfully_interrupted_impulse": "你已经成功打断了冲动！",
    "plans.please_start_a_positive_task": "请立刻开始一项正向任务（如冥想、运动、写日志），并为自己点赞！",
    "plans.close_modal": "关闭弹窗",
    "plans.still_cannot_control_myself": "我还是控制不住，重新来一遍",
    "plans.if_still_unable_to_control_yourself": "如果依然无法自控，请立刻联系好友/家人/导师，寻求帮助，不要独自承受！",

    // === 新增 profile 相关 ===
    "profile.title": "个人主页",
    "profile.subtitle": "记录你的成长与蜕变",
    "profile.motto_label": "个人签名宣言",
    "profile.motto_placeholder": "还没有设置个人签名宣言，点击编辑添加...",
    "profile.edit_motto": "编辑个人签名",
    "profile.joined_at": "加入时间",
    "profile.current_streak": "当前连续天数",
    "profile.max_streak": "历史最佳",
    "profile.total_days": "总打卡天数",
    "profile.success_rate": "成功率",
    "profile.tab_overview": "总览",
    "profile.tab_features": "功能",
    "profile.quick_entry": "功能快捷入口",
    "profile.quick_access": "快速访问常用功能",
    "profile.checkin": "每日打卡",
    "profile.checkin_desc": "记录今日状态",
    "profile.plans": "戒色方案",
    "profile.plans_desc": "个性化指导",
    "profile.leaderboard": "排行榜",
    "profile.leaderboard_desc": "查看排名",
    "profile.ai_coach": "AI助教",
    "profile.ai_coach_desc": "智能咨询",
    "profile.edit_name": "修改昵称",
    "profile.edit_name_placeholder": "请输入新昵称",
    "profile.edit_name_cancel": "取消",
    "profile.edit_name_save": "保存",
    "profile.edit_name_saving": "保存中...",
    "profile.edit_motto_dialog_title": "编辑个人签名宣言",
    "profile.edit_motto_dialog_desc": "写下你的戒色宣言，激励自己坚持",
    "profile.edit_motto_placeholder": "例如：我要成为更好的自己，戒色让我更强大！",
    "profile.edit_motto_close": "关闭",
    "profile.edit_motto_autosave": "输入后会自动保存",
    "profile.edit_motto_count": "{count}/200 字符",
    "profile.loading": "加载中...",
    "profile.please_login": "请先登录查看个人资料",
    "profile.save_success": "保存成功",
    "profile.save_failed": "保存失败",
    "profile.save_failed_desc": "个人签名保存失败，请重试",
    "profile.save_failed_error": "保存过程中出现错误，请重试",
    "profile.signout_success": "退出成功",
    "profile.signout_message": "您已成功退出登录",
    "profile.signout_failed": "退出失败",
    "profile.signout_error": "退出登录时发生错误",
    "profile.sign_out": "退出登录",

    // === 新增 pricing 相关 ===
    "pricing.free_features": [
      "完成色情成瘾等级测试",
      "每日打卡（基础版）",
      "免费试用 3 天的戒色方案",
      "AI助教每日提问 3 次",
      "可阅读部分文档片段"
    ],
    "pricing.premium_features": [
      "完整戒色方案",
      "所有资料文档与音频",
      "无限AI助教提问"
    ],

    // === 新增 profile overview 相关 ===
    "profile.progress": "戒色进度",
    "profile.progress_description": "您的戒色之路进度",
    "profile.current_level": "当前等级",
    "profile.level_prefix": "Lv.",
    "profile.next_level_days": "距离下一个等级还需",
    "profile.days": "天",

    // === 新增登录弹窗相关 ===
    "auth.login_title": "Log in to continue",
    "auth.login_description": "Choose your preferred login method, new users will automatically create an account.",
    "auth.google_login": "Log in with Google",
    "auth.github_login": "Log in with GitHub",
    "auth.continue_as_guest": "Continue as Guest",

    // === 首页 Hero 区相关 ===
    "home.hero_line1": "🌏 The world's first NoFap platform with video check-ins",
    "home.hero_line2": "💡 Awaken your willpower ignite the fire of self-growth",
    "home.hero_line3": "🌿 Witness every change in you with wisdom from Eastern traditions",
    "home.please_login": "请先登录以使用此功能",
  },
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.test": "Test",
    "nav.checkin": "Check-in",
    "nav.leaderboard": "Leaderboard",
    "nav.plans": "NoFap Plans",
    "nav.pricing": "Pricing",
    "nav.profile": "Profile",
    "nav.signin": "Log in",
    "nav.signup": "Sign Up",
    "nav.signout": "Sign Out",

    // Hero section
    "hero.title": "NoFap is Your Only Choice",
    "hero.subtitle":
      "Break free from pornography addiction, take control of your body and will.\nThrough scientific testing, daily check-ins, and behavior tracking,\nAwaken helps you rebuild focus, strength, and confidence step by step.",
    "hero.start_test": "Start Test",
    "hero.register": "Register Now",

    // Stats
    "stats.users": "users choose us",
    "stats.streak": "average streak days",
    "stats.success": "success rate",

    // Features
    "features.title": "Core Features",
    "features.subtitle": "We provide comprehensive NoFap support tools to help you build a healthy lifestyle",
    "features.test.title": "Professional Assessment",
    "features.test.desc": "Scientific evaluation of addiction levels to understand your true condition",
    "features.checkin.title": "Daily Check-in",
    "features.checkin.desc": "Record daily status and cultivate good habits",
    "features.leaderboard.title": "Leaderboard",
    "features.leaderboard.desc": "Progress together with other users, motivate each other",
    "features.community.title": "Community Support",
    "features.community.desc": "Join the NoFap community and get professional guidance",

    // Benefits
    "benefits.title": "Positive Changes\nfrom NoFap",
    "benefits.subtitle":
      "Scientific research shows that NoFap can significantly improve physical and mental health and quality of life.",
    "benefits.focus": "Improve focus and mental state",
    "benefits.relationships": "Enhance relationship quality",
    "benefits.willpower": "Strengthen self-control and willpower",
    "benefits.sleep": "Get better sleep quality",
    "benefits.efficiency": "Improve work and study efficiency",
    "benefits.lifestyle": "Build a healthy lifestyle",

    // CTA
    "cta.title": "Ready to start your NoFap journey?",
    "cta.subtitle":
      "Join our community with tens of thousands of users, regain control of your life, and embrace a better future.",
    "cta.test": "Free Test",
    "cta.register": "Register Now",

    // === 新增首页相关 ===
    "home.awaken_title": "Awaken NoFap Assistant",
    "home.awaken_subtitle": "Awaken your willpower. Track your journey with wisdom from Eastern traditions.",
    "home.awaken_slogan": "✨ 30 days to clear your addiction, trust and persistence will reverse your destiny! ✨",
    "home.start_test_button": "Start User Test",
    "home.world_first": "The world's first",
    "home.buddhist": "Buddhist",
    "home.nofap_site": "NoFap website supporting free video check-ins",
    "home.traditional_method": "Traditional Chinese NoFap methods refined from millions of real battles",
    "home.copyright": "© 2025 • Awaken NoFap Assistant. All rights reserved.",
    "home.features_title": "Awaken's Core Features",
    "home.features_subtitle": "Scientific methods, caring companionship, helping you regain new life",
    "home.feature_daily_checkin_title": "Daily Check-in",
    "home.feature_daily_checkin_desc": "Status, journal, and video check-in in one, persist in daily check-ins, record your progress journey, and build good habits",
    "home.feature_test_title": "Scientific Assessment",
    "home.feature_test_desc": "Through professional addiction testing assessment, understand your addiction level, and provide scientific basis for developing personalized NoFap plans",
    "home.feature_plans_title": "NoFap Plans",
    "home.feature_plans_desc": "Combined with scientific addiction testing, develop exclusive membership plans, significantly reduce sexual desire in 30 days, step by step, completely quit in 2 months, build physical foundation in 1 year, return to peak state",
    "home.feature_leaderboard_title": "Leaderboard",
    "home.feature_leaderboard_desc": "Show the top 10 NoFap heroes nationwide, strive to be a continuous NoFap hero, work together with like-minded friends, motivate each other to grow",
    "home.about_desc": "Awaken: A NoFap platform driven by scientific testing, helping users regain new life.",

    // === 新增首页标签相关 ===
    "home.tag_video_checkin": "Video Check-in",
    "home.tag_free_use": "Free Use",
    "home.tag_buddhist": "Buddhist NoFap",
    "home.tag_gpt": "GPT-3.5 Turbo",

    // === 新增隐私政策相关 ===
    "privacy.title": "Privacy Policy",
    "privacy.collection.title": "Information Collection",
    "privacy.collection.desc": "We only collect necessary information you provide voluntarily, including email address, basic information such as username, for account creation and service provision.",
    "privacy.usage.title": "Information Usage",
    "privacy.usage.desc": "Your personal information is only used for: providing NoFap assistant services, recording check-in progress, generating personalized suggestions, sending important notifications.",
    "privacy.protection.title": "Information Protection",
    "privacy.protection.desc": "We use industry-standard security measures to protect your data, including encrypted storage and secure transmission.",
    "privacy.third_party.title": "Third-Party Services",
    "privacy.third_party.desc": "We use third-party login services like Google and GitHub, which have their own privacy policies. We do not sell your personal information to third parties.",
    "privacy.deletion.title": "Data Deletion",
    "privacy.deletion.desc": "You can contact us at any time to delete your account and related data. After deletion, your personal information will be permanently removed from our system.",
    "privacy.contact.title": "Contact Us",
    "privacy.contact.desc": "If you have any questions about our privacy policy, please contact us via the feedback function within the platform.",
    "privacy.last_updated": "Last Updated: January 2025",

    // === 新增AI助教相关 ===
    "ai.title": "AI NoFap Coach",
    "ai.unlimited": "Unlimited Conversation",
    "ai.remaining_today": "Remaining Today",
    "ai.premium": "Premium",
    "ai.free": "Free",
    "ai.today_messages": "Messages Today",
    "ai.unlimited_use": "Unlimited Use",
    "ai.remaining": "Remaining",
    "ai.messages": "messages",
    "ai.quick_replies_title": "Quick Questions",

    // === 新增AI助教快速提问相关 ===
    "ai.quick_reply_urges": "How to deal with NoFap urges?",
    "ai.quick_reply_insomnia": "What to do if you have insomnia during NoFap?",
    "ai.quick_reply_habits": "How to establish healthy habits?",
    "ai.quick_reply_recovery": "Physical recovery after NoFap",
    "ai.quick_reply_relapse": "How to avoid relapse?",

    // === 新增测试结果概览相关 ===
    "home.test_overview_title": "Test Overview",
    "home.retest_button": "Retest",
    "home.test_score": "Test Score",
    "home.dependency_level": "Dependency Level",
    "home.daily_tasks": "Daily Tasks",
    "home.start_exclusive_plan": "Start your exclusive daily plan",
    "home.enter_nofap_plan": "Enter NoFap Plan",
    "home.join_premium_suggestion": "Suggest joining the exclusive premium plan, NoFap for 30 days can take effect",
    "home.learn_membership_details": "Learn about membership details",

    // === 新增每日推送相关 ===
    "daily_push.title": "Daily Exclusive Push",
    "daily_push.member_exclusive": "Member Exclusive",
    "daily_push.unlock_title": "Unlock Daily Exclusive Push",
    "daily_push.unlock_desc": "Become a member to get daily selected NoFap quotes, growth advice, and spiritual nourishment",
    "daily_push.preview_quote": "True growth is not about defeating others, but about surpassing yesterday's self.",
    "daily_push.preview_label": "— Member Exclusive Content Preview",
    "daily_push.footer": "Daily Update · Exclusive Content",

    // === 新增底部导航相关 ===
    "footer.about": "About",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.tools": "Tools",
    "footer.test": "Addiction Test",
    "footer.checkin": "Daily Check-in",

    // === 新增方案页相关 ===
    "plans.emergency_button": "Emergency! Click for Self-Rescue",
    "plans.emergency.cold_water": "Cold Water Shock",
    "plans.emergency.cold_water_cmd": "Go take a cold shower immediately! Rinse your head and face with cold water until you feel fully awake.",
    "plans.emergency.cold_water_reason": "Cold stimulation can quickly interrupt the brain's impulse circuit and restore your rationality.",
    "plans.emergency.breathing": "Deep Breathing x30",
    "plans.emergency.breathing_cmd": "Now, take 30 deep breaths. Inhale slowly, exhale slowly each time.",
    "plans.emergency.breathing_reason": "Deep breathing calms your body and mind, reducing physiological urges.",
    "plans.emergency.pepper": "Chili Stimulation",
    "plans.emergency.pepper_cmd": "If you have super spicy chili at home, eat one now to feel intense stimulation.",
    "plans.emergency.pepper_reason": "Strong taste stimulation can shift your attention and break the desire loop.",
    "plans.emergency.environment": "Change Environment",
    "plans.emergency.environment_cmd": "Leave the room immediately, go to a crowded outdoor place, even just downstairs, until the urge fades.",
    "plans.emergency.environment_reason": "Seeing people and changing environment will automatically switch your brain to social and rational mode.",
    "plans.emergency.mantra": "Spiritual Shift",
    "plans.emergency.mantra_cmd": "Now, chant the Zhunti Mantra 7 times, or loudly recite your favorite motivational quote.",
    "plans.emergency.mantra_reason": "Use positive sound and belief to clear all distracting thoughts from your mind.",
    "plans.level.mild": "Mild",
    "plans.level.moderate": "Moderate",
    "plans.level.severe": "Severe",
    "plans.overview_title": "Test Overview",
    "plans.retest": "Retake Test",
    "plans.test_score": "Test Score",
    "plans.addiction_level": "Addiction Level",
    "plans.daily_tasks": "Daily Tasks",
    "plans.current_streak": "Current Streak",
    "plans.current_level": "Current Level",
    "plans.todays_progress": "Today's Progress",
    "plans.free_tasks": "Free Tasks",
    "plans.addiction_plan": "Addiction Plan",
    "plans.premium_tasks": "Premium Exclusive Tasks",
    "plans.advanced_tasks": "advanced tasks",
    "plans.premium_exclusive_tasks": "Premium Exclusive Tasks",

    // === 新增任务相关 ===
    "task.daily_checkin": "Daily Check-in",
    "task.daily_checkin_desc": "Record today's status",
    "task.journal": "Recovery Journal",
    "task.journal_desc": "Record today's insights",
    "task.video_checkin": "Video Check-in",
    "task.video_checkin_desc": "Record video sharing",
    "task.audio_listen": "Listen to Recovery Audio (Episodes 1-{count})",
    "task.audio_desc": "Listen to {count} recovery audio episodes to boost willpower",
    "task.article_read": "Read NoFap Articles (Chapters 1-{count})",
    "task.article_desc": "Read {count} NoFap articles to gain wisdom",
    "task.mantra_chant": "Chant Zhunti Mantra {count} times",
    "task.mantra_desc": "Purify mind, strengthen focus, today's goal: {count} times",
    "task.meditation": "Meditation (10-20 min)",
    "task.meditation_desc": "Mindful practice, gratitude meditation, calm desires",
    "task.meditation_instruction": "Find a quiet, clean place, sit cross-legged, close your eyes, focus on breathing, recall people and things worth being grateful for in your life, let your heart fill with warmth and strength. Recommended 10-20 minutes each time.",
    "task.sleep": "Auspicious Sleep (Yang Restoration)",
    "task.sleep_desc": "Lie on back, hands behind waist, feet together, feel warm flow",
    "task.sleep_instruction": "Lie on your back, hands naturally behind your waist, feet together, close your eyes, feel a warm energy flow in your body, your body will quickly warm up. This is the traditional Chinese Yang restoration method, helpful for restoring energy and calming desires.",
    // === New: Aerobic Exercise ===
    "task.exercise": "Aerobic Exercise 10min",
    "task.exercise_desc": "Enhance physical fitness, absorb natural energy",
    "task.exercise_instruction": "Do 10 minutes of aerobic exercise, such as running, skipping rope, brisk walking, etc., to increase heart rate and improve fitness. Recommended to run in the park in the morning, hug a tree, or do outdoor activities to absorb natural energy.",

    // === 新增引导页相关 ===
    "onboarding.prev": "Previous",
    "onboarding.next": "Next",
    "onboarding.start_using": "Start Using Awaken",
    "onboarding.community": "Join over {count}+ users in recovery community",

    // === 新增个人资料页相关 ===
    "profile.title": "My Profile",
    "profile.description": "Personal information and NoFap progress",
    "profile.loading": "Loading...",
    "profile.login_required": "Please login to view your profile",
    "profile.checkin": "Check-in",
    "profile.load_failed": "Load Failed",
    "profile.load_error": "Unable to load profile, please try again later",
    "profile.signout_success": "Sign Out Success",
    "profile.signout_message": "You have successfully signed out",
    "profile.signout_failed": "Sign Out Failed",
    "profile.signout_error": "Error occurred while signing out",
    "profile.upload_failed": "Upload Failed",
    "profile.save_failed": "Save Failed",
    "profile.avatar_updated": "Avatar Updated",
    "profile.name_updated": "Name Updated",
    "profile.trend_30_days": "30-Day Check-in Trend",
    "profile.no_data": "No Data",

    // === 新增日志相关 ===
    "journal.records": "Journal Records",
    "journal.no_records": "No journal records",
    "journal.content": "Journal Content",
    "journal.readonly": "Read Only",
    "journal.edit_again": "Edit Again",
    "journal.edit": "Edit Journal",
    "journal.editing": "Editing",
    "journal.cancel": "Cancel",
    "journal.placeholder": "Record your feelings and thoughts...",
    "journal.save": "Save Journal",

    // === 新增AI助教相关 ===
    "ai.welcome": "Hello! I'm your AI NoFap Coach, dedicated to providing you with NoFap guidance and support. I can help you:\n\n• Answer NoFap-related questions\n• Provide psychological support and advice\n• Share NoFap techniques and methods\n• Analyze your NoFap progress\n\nHow can I help you today?",
    "ai.input_placeholder": "Enter your question...",
    "ai.input_placeholder_free": "Enter your question... (Free users: 5 messages/day)",
    "ai.upgrade_tip": "Upgrade to premium for unlimited AI coaching",
    "ai.limit_reached": "You've reached today's free message limit (5). Upgrade to premium for unlimited AI coaching!",

    // === 新增公告栏相关 ===
    "announcement.motd": "🚀 This is our evolving MVP version. We're continuously refining and improving our features. Your feedback is incredibly valuable and will directly help us grow faster. If you encounter any issues or have suggestions, please don't hesitate to reach out. Thank you for your patience and support as we build a better platform together!",

    // === 新增设置页相关 ===
    "setup.title": "System Settings",
    "setup.create_bucket": "Create Avatar Storage Bucket",
    "setup.created": "Created",
    "setup.not_created": "Not Created",
    "setup.creating": "Creating...",
    "setup.desc": "This page is for system setup tasks such as creating necessary storage buckets.\nAfter completing setup, you can return to the application to continue using it.",

    // === 新增引导页相关 ===
    "intro.welcome": "Welcome to Awaken",
    "intro.start_journey": "Start your <strong>journey of rebirth</strong><br/>Regain control of your life<br/><small>NoFap recovery methods based on scientific research</small>",
    "intro.truth": "Know the Truth",
    "intro.porn_harm": "Porn is <strong>quietly harming</strong> your brain<br/>Affecting focus, memory, and decision-making<br/><small>Neuroscience research: Long-term viewing reduces brain gray matter density</small>",
    "intro.damage": "Physical and Mental Damage",
    "intro.anxiety_depression": "Long-term viewing causes <strong>anxiety and depression</strong><br/>Affects relationships and self-confidence<br/><small>Psychology research shows: Closely related to social anxiety symptoms</small>",

    // === 新增反馈相关 ===
    "feedback.title": "User Feedback",
    "feedback.subtitle": "Your opinion matters to us",
    "feedback.email_label": "Email Address (Optional)",
    "feedback.email_placeholder": "your@email.com",
    "feedback.feedback_label": "Your suggestions or feedback",
    "feedback.feedback_placeholder": "Please share your experience, suggestions, or issues encountered...",
    "feedback.rating_label": "Overall Rating",
    "feedback.submit": "Submit Feedback",
    "feedback.submitting": "Submitting...",
    "feedback.success_title": "Thank you for your feedback",
    "feedback.success_message": "We have received your opinion and will carefully consider it for continuous improvement.",
    "feedback.submit_another": "Submit Another Feedback",

    // === 新增定价页相关 ===
    "pricing.title": "Pricing & Membership Plans",
    "pricing.subtitle": "Choose the right NoFap plan for you. Try for free or upgrade to unlock all features.",
    "pricing.free_plan": "Free Plan",
    "pricing.premium_plan": "Premium Plan",
    "pricing.free_desc": "Basic features are always free, perfect for beginners.",
    "pricing.premium_desc": "Unlock all exclusive features, get personalized guidance and deep growth.",
    "pricing.forever": "Forever Free",
    "pricing.recommended": "Recommended",
    "pricing.per_month": "/month",
    "pricing.continuous_update": "Continuous updates with more premium content",
    "pricing.payment_error": "Payment error, please try again or contact support.",
    "pricing.payment_success": "Membership will be activated automatically after payment.",
    "pricing.member_access": "Members can access all exclusive content immediately.",
    "pricing.cancel_info": "Membership can be cancelled anytime, 7-day no-questions-asked refund guarantee.",
    "pricing.contact_support": "Contact support if you have any questions.",
    "pricing.free_trial": "Free Trial",
    "pricing.join_membership": "Join Membership",
    "pricing.benefit.free.status": "Free status check-in",
    "pricing.benefit.free.journal": "Free journal log",
    "pricing.benefit.free.video": "3 free video check-ins per month",
    "pricing.benefit.free.ai": "5 free AI assistant uses per month",
    "pricing.benefit.premium.all_free": "All Free Plan benefits",
    "pricing.benefit.premium.daily_push": "Daily premium content push",
    "pricing.benefit.premium.video": "Unlimited video check-ins",
    "pricing.benefit.premium.ai": "Unlimited AI assistant uses",
    "pricing.benefit.premium.plan": "Personalized NoFap plan",
    "pricing.benefit.premium.analytics": "Advanced analytics",

    // === 新增打卡页面相关 ===
    "checkin.title": "Daily Check-in",
    "checkin.subtitle": "Record your abstinence journey, every day is important",
    "checkin.loading": "Loading...",
    "checkin.pleaseLogin": "Please login first",
    "checkin.currentStreak": "Current consecutive\nabstinence days",
    "checkin.currentConsecutive": "Current consecutive",
    "checkin.maxStreak": "Historical maximum\nconsecutive days",
    "checkin.historicalBest": "Historical best",
    "checkin.successRate": "Success rate",
    "checkin.basedOnStreak": "Based on consecutive days",
    "checkin.totalDays": "Total check-in days",
    "checkin.accumulatedRecord": "Accumulated record",

    // === 新增打卡模态框相关 ===
    "checkinModal.checkin": "Check-in",
    "checkinModal.reset": "Reset",
    "checkinModal.statusAndLog": "Status & Log",
    "checkinModal.video": "Video",
    "checkinModal.todayStatus": "Today's Status",
    "checkinModal.success": "Stayed clean today!",
    "checkinModal.failed": "Relapsed today!",
    "checkinModal.todayReflection": "Today's Reflection (Optional)",
    "checkinModal.reflectionPlaceholder": "Record today's mood, reflections, or challenges encountered...",
    "checkinModal.videoRecord": "Video Record (Optional)",
    "checkinModal.videoUploaded": "Video uploaded",
    "checkinModal.reRecord": "Re-record",
    "checkinModal.saveCheckin": "Save Check-in",
    "checkinModal.saving": "Saving...",
    "checkinModal.uploading": "Uploading...",
    "checkinModal.resetting": "Resetting...",
    "checkinModal.userNotLoggedIn": "User not logged in, please login again",
    "checkinModal.saveFailed": "Save failed",
    "checkinModal.resetFailed": "Reset failed",
    "checkinModal.videoUploadSuccess": "Video upload successful!",
    "checkinModal.existingRecordCleared": "Existing record cleared, you can fill in again",
    "checkin.saveSuccess": "Check-in saved successfully!",

    // === 新增通用提示相关 ===
    "common.loadFailed": "Load Failed",
    "common.saveFailed": "Save Failed",
    "common.animationLoadFailed": "Animation Load Failed",
    "common.userVerificationFailed": "User verification failed, please login again",
    "common.loadDataFailed": "Load data failed",
    "common.resetFailed": "Reset failed",

    // === 新增日历组件相关 ===
    "calendar.months.1": "January",
    "calendar.months.2": "February", 
    "calendar.months.3": "March",
    "calendar.months.4": "April",
    "calendar.months.5": "May",
    "calendar.months.6": "June",
    "calendar.months.7": "July",
    "calendar.months.8": "August",
    "calendar.months.9": "September",
    "calendar.months.10": "October",
    "calendar.months.11": "November",
    "calendar.months.12": "December",
    "calendar.weekdays.0": "Sun",
    "calendar.weekdays.1": "Mon",
    "calendar.weekdays.2": "Tue",
    "calendar.weekdays.3": "Wed",
    "calendar.weekdays.4": "Thu",
    "calendar.weekdays.5": "Fri",
    "calendar.weekdays.6": "Sat",

    // === 新增日历详细内容相关 ===
    "calendar.year": "",
    "calendar.today": "Today",
    "calendar.makeup": "Makeup",
    "calendar.todayTooltip": "Today you can operate normally",
    "calendar.legend.today": "Today",
    "calendar.legend.success": "Success",
    "calendar.legend.failed": "Failed",
    "calendar.legend.makeup": "Can makeup",
    "calendar.legend.journal": "Journal",
    "calendar.legend.video": "Video",
    "calendar.rules.today": "Today you can check-in and modify normally",
    "calendar.rules.recent": "Past 3 days can makeup check-in",
    "calendar.rules.old": "Records over 3 days can only be viewed",
    "calendar.rules.future": "Future dates cannot be operated",
    // === 新增日历权限 reason 相关 ===
    "calendar.reason.makeup": "You can make up check-in",
    "calendar.reason.today": "You can operate normally today",
    "calendar.reason.future": "Future dates cannot be operated",
    "calendar.reason.old_with_data": "Only viewable",
    "calendar.reason.old_no_data": "Makeup period expired",
    "calendar.reason.unknown": "Not operable",

    // === 新增排行榜页面相关 ===
    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "Stay clean, become a better self",
    "leaderboard.me": "Me",
    "leaderboard.myRank": "My rank: {rank}",
    "leaderboard.currentStreak": "Current consecutive streak",
    "leaderboard.days": "days",
    "leaderboard.user": "User",
    "leaderboard.anonymous": "Anonymous",
    "leaderboard.hero": "NoFap Hero",
    "leaderboard.currentStreakShort": "Current streak",
    "leaderboard.noData": "No leaderboard data yet",
    "leaderboard.beFirst": "Be the first to make the list!",

    // === 新增 plans 戒色方案页面相关 ===
    "plans.title": "NoFap Plan",
    "plans.stage1": "Initial Adaptation",
    "plans.stage1_days": "Days 1-20",
    "plans.stage2": "Steady Progress",
    "plans.stage2_days": "Days 21-59",
    "plans.stage3": "Deep Transformation",
    "plans.stage3_days": "Days 60-179",
    "plans.stage4": "Consolidation",
    "plans.stage4_days": "Day 180+",
    "plans.emergency.cold_water": "Cold Shower Shock",
    "plans.emergency.cold_water_cmd": "Take a cold shower immediately! Rinse your head and face with cold water until you feel fully awake.",
    "plans.emergency.cold_water_reason": "Cold stimulation can quickly interrupt the brain's impulse circuit and restore your rationality.",
    "plans.emergency.breathing": "Deep Breathing x30",
    "plans.emergency.breathing_cmd": "Now, take 30 deep breaths. Inhale slowly, exhale slowly each time.",
    "plans.emergency.breathing_reason": "Deep breathing calms your body and mind, reducing physiological urges.",
    "plans.emergency.pepper": "Chili Stimulation",
    "plans.emergency.pepper_cmd": "If you have super spicy chili at home, eat one now to feel intense stimulation.",
    "plans.emergency.pepper_reason": "Strong taste stimulation can shift your attention and break the desire loop.",
    "plans.emergency.environment": "Change Environment",
    "plans.emergency.environment_cmd": "Leave the room immediately, go to a crowded outdoor place, even just downstairs, until the urge fades.",
    "plans.emergency.environment_reason": "Seeing people and changing environment will automatically switch your brain to social and rational mode.",
    "plans.emergency.mantra": "Spiritual Shift",
    "plans.emergency.mantra_cmd": "Now, chant the Zhunti Mantra 7 times, or loudly recite your favorite motivational quote.",
    "plans.emergency.mantra_reason": "Use positive sound and belief to clear all distracting thoughts from your mind.",
    "plans.unlock_full": "Unlock the full NoFap plan",
    "plans.unlock_desc": "Upgrade to premium to get {count} advanced tasks, including professional audio, article reading, video check-in, and more.",
    "plans.upgrade_now": "Upgrade Now",
    "plans.audio.lesson1": "NoFap Audio - Lesson 1",
    "plans.audio.lesson2": "NoFap Audio - Lesson 2",
    "plans.audio.lesson3": "NoFap Audio - Lesson 3",
    "plans.article.chapter1": "Introduction + Chapter 1",
    "plans.article.chapter2": "Chapter 2",
    "plans.article.chapter3": "Chapter 3",
    "plans.article.chapter4": "Chapter 4",
    "plans.article.chapter5": "Chapter 5",
    "plans.article.chapter6": "Chapter 6",
    "plans.article.title": "Back to Light - NoFap Guide",
    "plans.article.desc": "A professional NoFap guidebook with scientific methods and practical tips.",
    "plans.mantra.title": "Zhunti Mantra",
    "plans.mantra.desc": "Zhunti Mantra, purifies the mind and strengthens willpower.",
    "plans.mantra.note": "This is the Zhunti Mantra with pinyin. Chant along by following the Chinese characters and their pronunciation. Even if you don't understand Chinese, focus on the sound and intention. Consistent chanting can help purify the mind and strengthen your willpower.",
    "plans.level.mild": "Mild",
    "plans.level.moderate": "Moderate",
    "plans.level.severe": "Severe",


    "plans.premium_features": "Premium Exclusive Features",
    "plans.personalized_guidance": "Personalized Guidance",
    "plans.customized_plan": "Customized NoFap plan based on test results",
    "plans.ai_analysis": "AI intelligent analysis and suggestions",
    "plans.online_counseling": "Professional online psychological counseling",
    "plans.progress_tracking": "Personal progress tracking and analysis reports",
    "plans.advanced_tools": "Advanced Tools",
    "plans.meditation_audio": "Meditation audio library (50+ professional audios)",
    "plans.nofap_books": "NoFap electronic books (20+ professional books)",
    "plans.emergency_help": "Emergency help function",
    "plans.community_vip": "Community VIP exclusive area communication",
    "plans.upgrade_to_premium": "Upgrade to Premium to unlock all features",
    "plans.upgrade_to_premium_title": "Upgrade to Premium to Unlock Advanced Features",
    "plans.premium_exclusive_features": "Premium Exclusive Features",
    "plans.professional_nofap_audio": "Professional NoFap audio guidance",
    "plans.nofap_knowledge_article": "NoFap knowledge article library",
    "plans.video_checkin": "Video check-in function",
    "plans.personalized_nofap_plan": "Personalized NoFap plan",
    "plans.maybe_later": "Maybe Later",
    "plans.nofap_audio_library": "NoFap Audio Library",
    "plans.click_to_play": "Click to play",
    "plans.playing": "Playing",
    "plans.professional_nofap_audio_desc": "Professional NoFap audio guidance to help you establish the correct cognition and habits. It is recommended to listen to one lesson per day, gradually changing.",
    "plans.nofap_article_library": "NoFap Article Library",
    "plans.mantra_practice": "Mantra Practice",
    "plans.zhunti_mantra_image": "Zhunti Mantra Image",
    "plans.chanting_method": "Chanting Method",
    "plans.find_quiet_place": "Find a quiet place, maintain mental purity",
    "plans.fold_hands": "Fold your hands, focus on chanting the mantra",
    "plans.chant_7_or_21_times": "Chant 7 times or 21 times each time",
    "plans.chant_while_visualizing_master_zhunti_compassionate_light": "Chant while visualizing the compassionate light of Master Zhunti",
    "plans.pray_for_mind_purification_and_willpower_strengthening": "Pray for purification of the mind, strengthening of willpower",
    "plans.devote_yourself_to_chanting_zhunti_mantra_with_sincerity": "Devote yourself to chanting the Zhunti Mantra with sincerity, which can purify the mind, strengthen willpower, and help overcome bad habits.",
    "plans.it_is_recommended_to_chant_once_in_the_morning_and_once_in_the_evening_every_day": "It is recommended to chant once in the morning and once in the evening every day,",
    "plans.with_perseverance": "with perseverance.",
    "plans.mark_as_completed": "Mark as Completed",
    "plans.task_instructions": "Task Instructions",
    "plans.i_understand": "I Understand",
    "plans.emergency_self_help": "Emergency Self-Help",
    "plans.end": "End",
    "plans.completed_next_step": "Completed, Next Step",
    "plans.cannot_skip_step": "You cannot skip any step, complete it!",
    "plans.successfully_interrupted_impulse": "You have successfully interrupted the impulse!",
    "plans.please_start_a_positive_task": "Please start a positive task (such as meditation, exercise, writing a diary) and give yourself a pat on the back!",
    "plans.close_modal": "Close Modal",
    "plans.still_cannot_control_myself": "I still cannot control myself, let's try again",
    "plans.if_still_unable_to_control_yourself": "If you are still unable to control yourself, please contact your friends/family/mentor for help, do not bear it alone!",

    // === 新增 profile 相关 ===
    "profile.title": "Profile",
    "profile.subtitle": "Track your growth and transformation",
    "profile.motto_label": "Personal Motto",
    "profile.motto_placeholder": "No personal motto set yet, click to add...",
    "profile.edit_motto": "Edit Personal Motto",
    "profile.joined_at": "Joined At",
    "profile.current_streak": "Current Streak",
    "profile.max_streak": "Best Streak",
    "profile.total_days": "Total Check-in Days",
    "profile.success_rate": "Success Rate",
    "profile.tab_overview": "Overview",
    "profile.tab_features": "Features",
    "profile.quick_entry": "Quick Access",
    "profile.quick_access": "Quickly access common features",
    "profile.checkin": "Daily Check-in",
    "profile.checkin_desc": "Record today's status",
    "profile.plans": "NoFap Plan",
    "profile.plans_desc": "Personalized Guidance",
    "profile.leaderboard": "Leaderboard",
    "profile.leaderboard_desc": "View Rankings",
    "profile.ai_coach": "AI Coach",
    "profile.ai_coach_desc": "Intelligent Consultation",
    "profile.edit_name": "Edit Nickname",
    "profile.edit_name_placeholder": "Enter new nickname",
    "profile.edit_name_cancel": "Cancel",
    "profile.edit_name_save": "Save",
    "profile.edit_name_saving": "Saving...",
    "profile.edit_motto_dialog_title": "Edit Personal Motto",
    "profile.edit_motto_dialog_desc": "Write your NoFap declaration to motivate yourself",
    "profile.edit_motto_placeholder": "E.g.: I want to be a better self, NoFap makes me stronger!",
    "profile.edit_motto_close": "Close",
    "profile.edit_motto_autosave": "Auto-save after input",
    "profile.edit_motto_count": "{count}/200 characters",
    "profile.loading": "Loading...",
    "profile.please_login": "Please login to view your profile",
    "profile.save_success": "Saved successfully",
    "profile.save_failed": "Save failed",
    "profile.save_failed_desc": "Failed to save personal motto, please try again",
    "profile.save_failed_error": "Error occurred during saving, please try again",
    "profile.signout_success": "Sign Out Success",
    "profile.signout_message": "You have successfully signed out",
    "profile.signout_failed": "Sign Out Failed",
    "profile.signout_error": "Error occurred while signing out",
    "profile.sign_out": "Sign Out",

    // === 新增 pricing 相关 ===
    "pricing.free_features": [
      "Complete pornography addiction level assessment",
      "Daily check-in (basic version)",
      "Free trial of 3-day NoFap plan",
      "AI coach: 3 questions per day",
      "Access to partial documentation"
    ],
    "pricing.premium_features": [
      "Complete NoFap plan",
      "All documentation and audio materials",
      "Unlimited AI coach questions"
    ],

    // === 新增 profile overview 相关 ===
    "profile.progress": "Progress",
    "profile.progress_description": "Your NoFap journey progress",
    "profile.current_level": "Current Level",
    "profile.level_prefix": "Lv.",
    "profile.next_level_days": "Days to next level",
    "profile.days": "days",

    // === 新增登录弹窗相关 ===
    "auth.login_title": "Log in to continue",
    "auth.login_description": "Choose your preferred login method, new users will automatically create an account.",
    "auth.google_login": "Log in with Google",
    "auth.github_login": "Log in with GitHub",
    "auth.continue_as_guest": "Continue as Guest",

    // === 首页 Hero 区相关 ===
    "home.hero_line1": "🌏 The world's first NoFap platform with video check-ins",
    "home.hero_line2": "💡 Awaken your willpower ignite the fire of self-growth",
    "home.hero_line3": "🌿 Witness every change in you with wisdom from Eastern traditions",
    "home.please_login": "Please log in to use this feature",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && (savedLanguage === "zh" || savedLanguage === "en")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  console.log("useLanguage context value:", context)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
