"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "zh" | "en"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  zh: {
    // 公告栏
    "announcement.motd": "🚀 这是Awaken的MVP版本，我们在持续打磨和完善功能。你的反馈对我们非常重要，将直接帮助平台成长。如果遇到问题或有建议，欢迎随时反馈。感谢你的支持与耐心！",
    
    // 个人页面
    "profile.title": "个人中心",
    "profile.subtitle": "管理你的个人信息和戒色进度",
    "profile.edit_avatar": "编辑头像",
    "profile.edit_name": "修改昵称",
    "profile.joined_at": "加入时间",
    "profile.motto_label": "个人签名宣言",
    "profile.motto_placeholder": "还没有设置个人签名宣言，点击编辑添加...",
    "profile.edit_motto": "编辑个人签名",
    "profile.sign_out": "退出登录",
    "profile.change_avatar": "修改头像",
    "profile.select_image": "选择图片",
    "profile.selected_file": "已选择的文件",
    "profile.supported_formats": "支持 JPG、PNG、GIF、WebP 格式，最大 5MB",
    "profile.cancel": "取消",
    "profile.uploading": "上传中...",
    "profile.save": "保存",
    "profile.new_name_placeholder": "请输入新昵称",
    "profile.saving": "保存中...",
    "profile.edit_motto_label": "编辑个人签名宣言",
    "profile.motto_inspiration": "写下你的戒色宣言，激励自己坚持",
    "profile.motto_example": "例如：我要成为更好的自己，戒色让我更强大！",
    "profile.characters": "字符",
    "profile.close": "关闭",
    "profile.auto_save": "输入后会自动保存",
    "profile.current_streak": "当前连续天数",
    "profile.max_streak": "历史最佳",
    "profile.total_days": "总打卡天数",
    "profile.success_rate": "成功率",
    "profile.tab_overview": "总览",
    "profile.tab_features": "功能",
    "profile.progress": "戒色进度",
    "profile.progress_description": "您的戒色之路进度",
    "profile.current_level": "当前等级",
    "profile.next_level_days": "距离下一个等级还需",
    "profile.days": "天",
    "profile.quick_entry": "功能快捷入口",
    "profile.quick_access": "快速访问常用功能",
    "profile.checkin": "每日打卡",
    "profile.checkin_desc": "记录今日状态",
    "profile.plans": "戒色方案",
    "profile.plans_desc": "个性化指导",
    "profile.leaderboard": "排行榜",
    "profile.leaderboard_desc": "查看排名",
    "profile.feature_community": "社区",
    "profile.feature_community_desc": "与其他用户交流分享",
    "profile.ai_coach": "AI助教",
    "profile.ai_coach_desc": "智能咨询",
    "profile.level_tooltip": `等级说明：\n- Lv.0：当前连签不足7天\n- Lv.1：连签满7天\n- Lv.2：连签满30天\n- Lv.3：连签满90天\n- Lv.4：连签满180天\n- Lv.5：连签满365天\n\n提升等级需要保持连续签到，达到对应天数即可升级。坚持打卡，解锁更高荣誉！`,

    // 排行榜页面
    "leaderboard.title": "排行榜",
    "leaderboard.subtitle": "与其他用户一起进步，互相激励",
    "leaderboard.myRank": "我的排名：第{rank}名",
    "leaderboard.myRankValue": "#{rank}",
    "leaderboard.currentStreak": "当前连续天数",
    "leaderboard.currentStreakShort": "连续天数",
    "leaderboard.days": "天",
    "leaderboard.hero": "本周英雄",
    // 方案页与任务（仅保留实际引用的key）
    "plans.stage1": "紧急自救",
    "plans.stage1_days": "1-20天",
    "plans.stage2": "习惯养成",
    "plans.stage2_days": "21-59天",
    "plans.stage3": "深度戒断",
    "plans.stage3_days": "60-179天",
    "plans.stage4": "长期稳定",
    "plans.stage4_days": "180天+",
    "plans.emergency.cold_water": "冷水冲澡",
    "plans.emergency.cold_water_cmd": "立即用冷水冲澡5-10分钟",
    "plans.emergency.cold_water_reason": "冷水能快速降低体温，减少性冲动",
    "plans.emergency.breathing": "深呼吸练习",
    "plans.emergency.breathing_cmd": "深呼吸10次，每次吸气4秒，呼气6秒",
    "plans.emergency.breathing_reason": "深呼吸能平静神经系统，缓解冲动",
    "plans.emergency.pepper": "闻辣椒粉",
    "plans.emergency.pepper_cmd": "闻一下辣椒粉或芥末",
    "plans.emergency.pepper_reason": "强烈气味能转移注意力，打断冲动",
    "plans.emergency.environment": "改变环境",
    "plans.emergency.environment_cmd": "立即离开当前环境，去公共场所",
    "plans.emergency.environment_reason": "环境改变能有效打断冲动循环",
    "plans.emergency.mantra": "默念戒色宣言",
    "plans.emergency.mantra_cmd": "默念你的戒色宣言10遍",
    "plans.emergency.mantra_reason": "宣言能强化意志，提醒戒色目标",
    "plans.audio.lesson1": "戒色基础知识",
    "plans.audio.lesson2": "应对冲动的技巧",
    "plans.audio.lesson3": "长期坚持的方法",
    "plans.level.mild": "轻度",
    "plans.level.moderate": "中度",
    "plans.level.severe": "重度",
    "plans.overview_title": "测试结果概览",
    "plans.test_score": "测试得分",
    "plans.addiction_level": "依赖等级",
    "plans.daily_tasks": "今日任务数",
    "plans.current_streak": "当前连续天数",
    "plans.current_level": "当前等级",
    "plans.todays_progress": "今日进度",
    "plans.days": "天",
    "plans.free_tasks": "免费任务",
    "plans.premium_tasks": "会员专属任务",
    "plans.premium_features": "会员专属功能",
    "plans.personalized_guidance": "个性化指导",
    "plans.customized_plan": "专属定制方案",
    "plans.ai_analysis": "AI智能分析",
    "plans.online_counseling": "在线咨询",
    "plans.progress_tracking": "进度追踪",
    "plans.advanced_tools": "进阶工具",
    "plans.meditation_audio": "冥想音频",
    "plans.nofap_books": "戒色书籍",
    "plans.emergency_help": "紧急自救",
    "plans.community_vip": "专属社群",
    "plans.retest": "重新测试",
    "task.completed": "已完成",
    "task.start": "开始任务",

    // 日历组件
    "calendar.months.1": "一月",
    "calendar.months.2": "二月",
    "calendar.months.3": "三月",
    "calendar.months.4": "四月",
    "calendar.months.5": "五月",
    "calendar.months.6": "六月",
    "calendar.months.7": "七月",
    "calendar.months.8": "八月",
    "calendar.months.9": "九月",
    "calendar.months.10": "十月",
    "calendar.months.11": "十一月",
    "calendar.months.12": "十二月",
    "calendar.weekdays.0": "日",
    "calendar.weekdays.1": "一",
    "calendar.weekdays.2": "二",
    "calendar.weekdays.3": "三",
    "calendar.weekdays.4": "四",
    "calendar.weekdays.5": "五",
    "calendar.weekdays.6": "六",

    // 定价页面
    "pricing.benefit.free.status": "基础打卡功能",
    "pricing.benefit.free.journal": "简单日记记录",
    "pricing.benefit.free.video": "基础视频功能",
    "pricing.benefit.free.ai": "每日5条AI咨询",
    "pricing.benefit.free.professional_test": "专业测试评估",
    "pricing.benefit.free.professional_analysis": "基础数据分析",
    "pricing.benefit.premium.all_free": "所有免费功能",
    "pricing.benefit.premium.daily_push": "每日个性化推送",
    "pricing.benefit.premium.video": "高级视频功能",
    "pricing.benefit.premium.ai": "无限AI咨询",
    "pricing.benefit.premium.plan": "个性化戒色方案",
    "pricing.benefit.premium.analytics": "详细数据分析",
    "pricing.benefit.premium.community": "专属社区支持",

 // 底部及导航登录组建
    "home.awaken_title": "Awaken觉醒",
    "home.about_desc": "Awaken觉醒，助你自律成长，重塑人生。",
    "footer.about": "关于我们",
    "footer.features": "功能介绍",
    "footer.pricing": "会员定价",
    "footer.tools": "实用工具",
    "footer.test": "戒瘾测试",
    "footer.checkin": "每日打卡",
    "home.copyright": "© 2024 Awaken觉醒 保留所有权利",
    "nav.settings": "设置",
    "nav.signout": "退出登录",

    // 反馈组件
    "feedback.title": "意见反馈",
    "feedback.subtitle": "帮助我们改进产品，提供更好的服务",
    "feedback.email_label": "邮箱地址",
    "feedback.email_placeholder": "请输入您的邮箱地址",
    "feedback.feedback_label": "反馈内容",
    "feedback.feedback_placeholder": "请详细描述您的问题或建议...",
    "feedback.rating_label": "满意度评分",
    "feedback.image_label": "上传截图",
    "feedback.image_placeholder": "选择图片文件",
    "feedback.image_uploading": "上传中...",
    "feedback.image_upload_failed": "上传失败",
    "feedback.image_remove": "移除图片",
    "feedback.submit": "提交反馈",
    "feedback.submitting": "提交中...",
    "feedback.success_title": "提交成功",
    "feedback.success_message": "感谢您的反馈，我们会认真处理",
    "feedback.submit_another": "继续反馈",

    // 日记编辑器
    "journal.records": "日记记录",
    "journal.no_records": "暂无记录",

    // 每日推送
    "daily_push.title": "每日推送",
    "daily_push.member_exclusive": "会员专享",
    "daily_push.footer": "今日建议",
    //补充
    "plans.upgrade_to_premium_title": "升级会员，解锁全部专属功能",
"plans.premium_exclusive_features": "会员专属功能",
"plans.professional_nofap_audio": "专业戒色音频课程",
"plans.nofap_knowledge_article": "精选戒色知识文章",
"plans.video_checkin": "视频打卡成长记录",
"plans.personalized_nofap_plan": "个性化戒色方案",
"plans.upgrade_now": "立即升级",
"plans.maybe_later": "以后再说",
"plans.upgrade_to_premium": "请升级会员解锁全部功能",
"plans.upgrade_button": "升级会员",

    // AI聊天组件
    "ai.welcome": "你好！我是你的AI戒色助教，有什么可以帮助你的吗？",
    "ai.quick_reply_recovery": "戒色恢复期注意事项",

    // 感谢页面
    "thankyou.title": "感谢您的支持！",
    "thankyou.subtitle": "您的反馈对我们非常重要",

    // 隐私政策
    "privacy.title": "隐私政策",

    // 首页英雄区
    "home.world_first": "世界上第一个<span class='highlight'>佛学</span>戒色社群",
    "home.buddhist": "佛学",
    "home.nofap_site": "戒色网站",
    "home.awaken_slogan": "30天助你清除色瘾，信任与坚持定将逆转命运！",
    "home.traditional_method": "融合中华传统文化和视频打卡记录",
    // 首页测试结果区
    "home.test_overview_title": "测试结果概览",
    "home.retest_button": "重新测试",
    "home.test_score": "测试得分",
    "home.dependency_level": "依赖等级",
    "home.daily_tasks": "今日任务数",
    "home.start_exclusive_plan": "开始专属方案",
    "home.enter_nofap_plan": "进入戒色方案",
    "home.hero_line1": "唤醒自律，重塑人生",
    //未登录英雄区
"home.hero_line2": "结合中国传统方法，重塑你的自律与能量",
"home.hero_line3": "✨跟随中国传统养生智慧，迈向真正的戒色觉醒✨",
"home.tag_video_checkin": "视频打卡",
"home.tag_free_use": "中医常识",
"home.tag_buddhist": "内在成长",
"home.tag_gpt": "AI助手",
"home.login_guide_title": "登录后体验完整功能",
"home.start_test_button": "开始戒瘾测试",

//中文补充
"auth.login_title": "登录 Awaken",
"auth.login_description": "请选择登录方式，数据将安全同步",
"auth.google_login": "使用 Google 登录",
"auth.github_login": "使用 GitHub 登录",
"auth.continue_as_guest": "游客体验",
"nav.signin": "登录",
"common.pleaseLoginToView": "请登录后查看",
"common.pleaseLoginToUse": "请登录后使用完整功能",
"common.loginButton": "立即登录",

"profile.features": "功能总览",
"profile.feature_daily_checkin": "每日打卡",
"profile.feature_daily_checkin_desc": "记录自律，见证成长",
"profile.feature_plans": "成长计划",
"profile.feature_plans_desc": "科学定制，循序渐进",
"profile.feature_leaderboard": "排行榜",
"profile.feature_leaderboard_desc": "与他人比拼，激发动力",
"profile.feature_ai_coach": "AI助理",
"profile.feature_ai_coach_desc": "智能陪伴，答疑解惑",
"profile.feature_settings": "设置",
"profile.feature_settings_desc": "个性化你的体验",

"plans.sample_tasks": "示例任务",
"plans.sample_task_1": "冥想练习",
"plans.sample_task_1_desc": "每天冥想10分钟，培养专注力",
"plans.sample_button": "开始任务",
"plans.sample_task_2": "运动健身",
"plans.sample_task_2_desc": "每天运动30分钟，增强体质",
"plans.sample_task_desc": "任务描述",

// AI 相关
"ai.remaining": "剩余",
"ai.messages": "条消息",
"ai.remaining_today": "今日剩余",

    // 首页限时活动区
    "home.limited_event_section.limited_event": "限时活动",
    "home.limited_event_section.challenge_title": "30天打卡挑战",
    "home.limited_event_section.challenge_desc": "加入我们的30天戒色打卡挑战，与数万名用户一起，用坚持的力量重塑自我！",
    "home.limited_event_section.challenge_days": "挑战天数",
    "home.limited_event_section.participants": "参与用户",
    "home.limited_event_section.success_rate": "成功率",
    "home.limited_event_section.daily_checkin": "每日打卡",
    "home.limited_event_section.daily_checkin_desc": "记录每日状态，培养良好习惯，建立戒色信心",
    "home.limited_event_section.community_support": "社区支持",
    "home.limited_event_section.community_support_desc": "与志同道合的朋友一起努力，互相激励成长",
    "home.limited_event_section.achievement_system": "成就系统",
    "home.limited_event_section.achievement_system_desc": "解锁专属徽章，记录你的成长历程",
    "home.limited_event_section.ai_guidance": "AI指导",
    "home.limited_event_section.ai_guidance_desc": "智能AI助教提供个性化建议和鼓励",
    "home.limited_event_section.start_challenge": "立即开始挑战",
    "home.limited_event_section.reward_note": "完成挑战可获得专属会员体验券",

    // 导航栏
    "nav.home": "首页",
    "nav.checkin": "打卡",
    "nav.leaderboard": "排行榜",
    "nav.community": "社群",
    "nav.plans": "戒色方案",
    "nav.pricing": "定价",
    "nav.profile": "我的",

    // 首页功能区
    "home.features_title": "核心功能亮点",
    "home.features_subtitle": "助你科学戒色，持续成长",
    "home.feature_daily_checkin_title": "每日打卡",
    "home.feature_daily_checkin_desc": "记录每日状态，养成好习惯，见证成长",
    "home.feature_test_title": "专业测试",
    "home.feature_test_desc": "科学评估依赖程度，量身定制方案",
    "home.feature_plans_title": "个性化方案",
    "home.feature_plans_desc": "根据测试结果推荐专属戒色计划",
    "home.feature_leaderboard_title": "排行榜",
    "home.feature_leaderboard_desc": "与万名用户同台竞技，激励进步",
    // 通用
    "common.loading": "加载中...",
    // 打卡页loading
    "checkin.loading": "加载中...",
    // 日历与打卡页
    "calendar.today": "今天",
    "calendar.makeup": "补卡",
    "calendar.legend.today": "今天",
    "calendar.legend.success": "成功",
    "calendar.legend.failed": "失败",
    "calendar.legend.makeup": "补卡",
    "calendar.legend.journal": "日记",
    "calendar.legend.video": "视频",
    "calendar.reason.future": "未来日期，无法打卡",
    "calendar.rules.today": "今天只能打一次卡",
    "calendar.rules.recent": "最近7天可补卡",
    "calendar.rules.old": "7天前无法补卡",
    "calendar.rules.future": "未来日期不可打卡",
    "checkin.title": "每日打卡",
    "checkin.subtitle": "坚持打卡，见证成长",
    "checkin.currentStreak": "当前连续天数",
    "checkin.currentConsecutive": "当前连续记录",
    "checkin.maxStreak": "历史最佳",
    "checkin.historicalBest": "历史最高连续天数",
    "checkin.successRate": "成功率",
    "checkin.basedOnStreak": "基于连续天数",
    "checkin.totalDays": "累计打卡天数",
    "checkin.accumulatedRecord": "累计记录",

    // AI助教功能区
    "ai.title": "AI助教",
    "ai.premium": "会员专享",
    "ai.unlimited": "无限次数",
    "ai.unlimited_use": "无限使用",
    "ai.today_messages": "今日消息数：{count}",
    "ai.quick_replies_title": "快捷提问：",
    "ai.input_placeholder": "请输入你的问题...",
    // AI助教快捷提问
    "ai.quick_reply_urges": "如何应对强烈冲动？",
    "ai.quick_reply_insomnia": "戒色期间失眠怎么办？",
    "ai.quick_reply_habits": "如何建立健康习惯？",
    "ai.quick_reply_relapse": "复发了怎么办？",

    // 社区功能页
    "community.title": "社区",
    "community.subtitle": "与志同道合的朋友一起交流成长",
    "community.premium": "会员专享",
    "community.post_placeholder": "分享你的想法、经验或提问...",
    "community.post": "发布",
    "community.post_success": "发布成功！",
    "community.post_fail": "发布失败，请重试",
    "community.days": "天",
    "home.join_premium_suggestion": "加入会员，解锁更多专属功能",
    "home.learn_membership_details": "了解会员详情",

    "daily_push.unlock_title": "解锁今日专属内容",
    "daily_push.unlock_desc": "升级会员，获取每日专属正念推送、冥想音频和成长建议。",
    "daily_push.preview_quote": "今日会员专属语录预览",
    "daily_push.preview_label": "会员专属",

    "community.premium_required_title": "会员专属社区",
    "community.premium_required_desc": "该功能仅限会员访问，升级会员即可加入高质量成长社群，获得更多支持与资源。",

    "community.upgrade_to_premium": "升级会员",
    "community.premium_feature_1": "加入专属成长社群",
    "community.premium_feature_2": "获得专家答疑与专属内容",
    "community.back_to_home": "返回首页",
    // 方案页与任务补充
    "task.daily_checkin": "每日打卡",
    "task.daily_checkin_desc": "记录今日状态，养成好习惯",
    "task.exercise": "户外散步30min",
    "task.exercise_desc": "清晨户外慢走30分钟，唤醒阳气",
    "task.audio_listen": "音频聆听",
    "task.audio_desc": "聆听冥想或课程音频",
    "task.article_read": "文章阅读",
    "task.article_desc": "阅读精选文章，增长见识",
    "task.mantra_chant": "咒语诵念",
    "task.mantra_desc": "每日诵念，增强意志",
    "task.meditation": "冥想练习",
    "task.meditation_desc": "进行冥想，放松身心",
    "task.sleep": "睡眠任务",
    "task.sleep_desc": "保证充足睡眠，恢复精力",
    "task.exercise_instruction": "选择一个安静、自然的环境，如公园、小树林、河边，进行30分钟的缓慢散步。\n步伐无需匆忙，脚步要轻，呼吸要深。途中可以用手轻轻抚摸树干、倾听鸟鸣、观察阳光洒在树叶上的光影变化。\n不要带耳机，不要刷手机，保持觉知地行走。可默念佛号或观想“清静、感恩、持守”，将心神安住于当下。\n这段散步不是锻炼，而是自然“充电”——通过与自然万物的接触，慢慢化解内心的躁动和欲望，重新感受身体的能量流动。\n小贴士：\n树木如法器，抚摸它们时，心要诚；风如开示，聆听它时，心要静。",
    "task.sleep_instruction": "晚上11点至凌晨3点，是人体被称为“内在冬季”的修复黄金期，此时阳气深藏、精气归根，是最关键的养生时段。建议你在晚上10点就放下手机，避免刺激神经。可以看看纸质书，或者练习“吉祥卧”，让心神平稳。\n10点半闭眼睡觉，力争在11点前进入深度睡眠，让身体顺利进入恢复模式，积蓄能量，养护阳气。",
    "plans.task_instructions": "任务说明",
    "plans.i_understand": "我已了解",
    "plans.nofap_audio_library": "戒色音频库",
    "plans.click_to_play": "点击播放",
    "plans.professional_nofap_audio_desc": "专业音频内容，助你科学戒色，提升自律力。",
    // 价格页补充
    "pricing.title": "会员定价",
    "pricing.subtitle": "选择最适合你的成长方案",
    "pricing.free_plan": "免费计划",
    "pricing.free_desc": "基础功能永久免费使用",
    "pricing.forever": "永久免费",
    "pricing.free_trial": "免费试用",
    "pricing.premium_plan": "会员计划",
    "pricing.premium_desc": "解锁全部高级功能，助你高效成长",
    "pricing.recommended": "推荐",
    "pricing.per_month": "/月",
    "pricing.join_membership": "立即开通会员",
    "pricing.continuous_update": "持续更新更多功能",
    "pricing.payment_success": "支付成功，欢迎加入会员！",
    "pricing.member_access": "会员专属权限已开启",
    "pricing.cancel_info": "随时可取消，自动续费",
    "pricing.contact_support": "如有疑问请联系客服",
    //补充
"task.daily_checkin_desc_moderate": "记录今日状态和日志",
"task.daily_checkin_desc_heavy": "记录今日状态、日志，并上传视频",
    // 方案页咒语与任务补充
    "plans.mantra_practice": "咒语修持",
    "plans.mantra.title": "准提神咒",
    "plans.mantra.desc": "每日诵念，增强意志力和正念",
    "plans.mantra.note": "建议每日早晚各念一次，持之以恒必有收获。",
    "plans.chanting_method": "念诵方法",
    "plans.find_quiet_place": "选择安静的环境，身心放松",
    "plans.fold_hands": "双手合十，端身正坐",
    "plans.chant_7_or_21_times": "念诵7或21遍",
    "plans.chant_while_visualizing_master_zhunti_compassionate_light": "观想准提佛母慈光加持",
    "plans.pray_for_mind_purification_and_willpower_strengthening": "祈愿内心清净，意志坚强",
    "plans.devote_yourself_to_chanting_zhunti_mantra_with_sincerity": "以虔诚心念诵准提神咒，",
    "plans.it_is_recommended_to_chant_once_in_the_morning_and_once_in_the_evening_every_day": "建议每天早晚各念一次，",
    "plans.with_perseverance": "持之以恒，必有收获。",
    "plans.mark_as_completed": "标记为已完成",
    "task.meditation_instruction": "冥想不只是平静内心的工具，更是一种滋养情绪的修行。每天静坐10～20分钟，闭上眼睛，关注呼吸。\n可以在心中默念你感恩的人、温暖的时刻，或者回忆让你感受到爱的细节——这一切会逐步融化内心的欲望，让你重建与生命的连接。",
    "task.auspicious_rest": "吉祥卧10min",
    "task.auspicious_rest_desc": "睡前右侧卧，修复阳气，安神助眠",
    "task.auspicious_rest_instruction": "找一个安静整洁的空间，在睡前或冥想前练习“吉祥卧”：\n身体侧卧，躺在右侧，双腿自然弯曲，左手轻放在左大腿上，右手托腮或轻垫在头下，闭眼放松。保持呼吸绵长柔缓，觉察腹部的起伏。\n这是佛陀的睡姿之一，象征清净、安稳、无贪无欲。练习中可观想身体如一朵白莲沉静地漂浮在水面上，远离妄想与执着。\n每次5–10分钟，能助眠、安神、稳欲，尤其适合夜晚。\n小贴士：\n姿势自然，心要敬重，如佛在卧，身亦安然。",
    "checkinModal.videoRecord": "视频打卡",
    "checkinModal.openCamera": "打开摄像头",
    "checkinModal.startRecording": "点击下方按钮开始录制",
    "checkinModal.stopRecording": "停止录制",
    "checkinModal.recordingTips": "录制时请保持手机稳定，录制完成后可保存视频。",
    "checkinModal.saveVideo": "保存视频",
    "checkinModal.cameraPermissionDenied": "无法访问摄像头，请检查权限设置。",
    "checkinModal.cameraLoading": "摄像头加载中...",
    "checkinModal.cameraError": "摄像头初始化失败，请重试。",
    "checkinModal.statusAndLog": "状态与日志",
"checkinModal.video": "视频打卡",
"checkinModal.checkin": "打卡",
"checkinModal.todayStatus": "今日状态",
"checkinModal.success": "守戒成功",
"checkinModal.reflectionPlaceholder": "写下你的反思、总结或今日感悟...",
"checkinModal.failed": "破戒",
"checkinModal.todayReflection": "日志记录",
"checkinModal.saveCheckin": "保存打卡",
"checkinModal.videoUploaded": "视频已上传",
"checkinModal.reRecord": "重新录制",
  },
  en: {
    // 公告栏
    "announcement.motd": "🚀 This is Awaken's MVP version, we are continuously polishing and improving features. Your feedback is very important to us and will directly help the platform grow. If you encounter problems or have suggestions, feel free to provide feedback. Thank you for your support and patience!",
    
    // 个人页面
    "profile.title": "Profile",
    "profile.subtitle": "Manage your personal information and NoFap progress",
    "profile.edit_avatar": "Edit Avatar",
    "profile.edit_name": "Edit Name",
    "profile.joined_at": "Joined",
    "profile.motto_label": "Personal Motto",
    "profile.motto_placeholder": "No personal motto set yet, click edit to add...",
    "profile.edit_motto": "Edit Motto",
    "profile.sign_out": "Sign Out",
    "profile.change_avatar": "Change Avatar",
    "profile.select_image": "Select Image",
    "profile.selected_file": "Selected File",
    "profile.supported_formats": "Supports JPG, PNG, GIF, WebP formats, max 5MB",
    "profile.cancel": "Cancel",
    "profile.uploading": "Uploading...",
    "profile.save": "Save",
    "profile.new_name_placeholder": "Enter new nickname",
    "profile.saving": "Saving...",
    "profile.edit_motto_label": "Edit Personal Motto",
    "profile.motto_inspiration": "Write your NoFap declaration to motivate yourself",
    "profile.motto_example": "Example: I want to become a better self, NoFap makes me stronger!",
    "profile.characters": "characters",
    "profile.close": "Close",
    "profile.auto_save": "Will auto-save after input",
    "profile.current_streak": "Current Streak",
    "profile.max_streak": "Best Streak",
    "profile.total_days": "Total Days",
    "profile.success_rate": "Success Rate",
    "profile.tab_overview": "Overview",
    "profile.tab_features": "Features",
    "profile.progress": "NoFap Progress",
    "profile.progress_description": "Your NoFap journey progress",
    "profile.current_level": "Current Level",
    "profile.next_level_days": "Days to next level",
    "profile.days": "days",
    "profile.quick_entry": "Quick Entry",
    "profile.quick_access": "Quick Access",
    "profile.checkin": "Daily Check-in",
    "profile.checkin_desc": "Record today's status",
    "profile.plans": "NoFap Plan",
    "profile.plans_desc": "Personalized guidance",
    "profile.leaderboard": "Leaderboard",
    "profile.leaderboard_desc": "View rankings",
    "profile.feature_community": "Community",
    "profile.feature_community_desc": "Connect and share with others",
    "profile.ai_coach": "AI Coach",
    "profile.ai_coach_desc": "Intelligent consultation",
    "profile.level_tooltip": `Level Guide:\n- Lv.0: Less than 7 consecutive check-ins\n- Lv.1: 7 consecutive check-ins\n- Lv.2: 30 consecutive check-ins\n- Lv.3: 90 consecutive check-ins\n- Lv.4: 180 consecutive check-ins\n- Lv.5: 365 consecutive check-ins\n\nKeep checking in to level up and unlock more honors!`,
//补充
"task.daily_checkin_desc": "Log today’s status",
"task.daily_checkin_desc_moderate": "Log today’s status and journal",
"task.daily_checkin_desc_heavy": "Log today’s status, journal, and upload a video",
    // 排行榜页面
    "leaderboard.title": "Leaderboard",
    "leaderboard.subtitle": "Progress together with other users and motivate each other",
    "leaderboard.myRank": "My Rank: #{rank}",
    "leaderboard.myRankValue": "#{rank}",
    "leaderboard.currentStreak": "Current Streak",
    "leaderboard.currentStreakShort": "Streak",
    "leaderboard.days": "days",
    "leaderboard.hero": "Hero of the Week",
    // Plans page & tasks (only keep actually used keys)
    "plans.stage1": "Emergency Self-Rescue",
    "plans.stage1_days": "1-20 days",
    "plans.stage2": "Habit Formation",
    "plans.stage2_days": "21-59 days",
    "plans.stage3": "Deep Withdrawal",
    "plans.stage3_days": "60-179 days",
    "plans.stage4": "Long-term Stability",
    "plans.stage4_days": "180+ days",
    "plans.emergency.cold_water": "Cold Shower",
    "plans.emergency.cold_water_cmd": "Take a cold shower for 5-10 minutes immediately",
    "plans.emergency.cold_water_reason": "Cold water quickly reduces body temperature and sexual urges",
    "plans.emergency.breathing": "Deep Breathing",
    "plans.emergency.breathing_cmd": "Take 10 deep breaths, inhale for 4 seconds, exhale for 6 seconds",
    "plans.emergency.breathing_reason": "Deep breathing calms the nervous system and relieves urges",
    "plans.emergency.pepper": "Smell Pepper",
    "plans.emergency.pepper_cmd": "Smell chili powder or mustard",
    "plans.emergency.pepper_reason": "Strong odors can distract attention and interrupt urges",
    "plans.emergency.environment": "Change Environment",
    "plans.emergency.environment_cmd": "Leave the current environment immediately, go to a public place",
    "plans.emergency.environment_reason": "Environmental change can effectively interrupt the urge cycle",
    "plans.emergency.mantra": "Recite NoFap Declaration",
    "plans.emergency.mantra_cmd": "Recite your NoFap declaration 10 times",
    "plans.emergency.mantra_reason": "Declaration strengthens willpower and reminds of NoFap goals",
    "plans.audio.lesson1": "NoFap Basics",
    "plans.audio.lesson2": "Urge Management Techniques",
    "plans.audio.lesson3": "Long-term Persistence Methods",
    "plans.level.mild": "Mild",
    "plans.level.moderate": "Moderate",
    "plans.level.severe": "Severe",
    "plans.overview_title": "Test Overview",
    "plans.test_score": "Test Score",
    "plans.addiction_level": "Dependency Level",
    "plans.daily_tasks": "Today's Tasks",
    "plans.current_streak": "Current Streak",
    "plans.current_level": "Current Level",
    "plans.todays_progress": "Today's Progress",
    "plans.days": "days",
    "plans.free_tasks": "Free Tasks",
    "plans.premium_tasks": "Premium Tasks",
    "plans.premium_features": "Premium Features",
    "plans.personalized_guidance": "Personalized Guidance",
    "plans.customized_plan": "Customized Plan",
    "plans.ai_analysis": "AI Analysis",
    "plans.online_counseling": "Online Counseling",
    "plans.progress_tracking": "Progress Tracking",
    "plans.advanced_tools": "Advanced Tools",
    "plans.meditation_audio": "Meditation Audio",
    "plans.nofap_books": "NoFap Books",
    "plans.emergency_help": "Emergency Help",
    "plans.community_vip": "Community VIP",
    "plans.retest": "Retest",
    "task.completed": "Completed",
    "task.start": "Start Task",

    // 日历组件
    "calendar.months.1": "January",
    "calendar.months.2": "February",
    "calendar.months.3": "March",
    "calendar.months.4": "April",
    "calendar.months.5": "May",
    "calendar.months.6": "June",
    "calendar.months.7": "July",
    "calendar.months.8": "August",
    "calendar.months.9": "September",
    "calendar.months.10": "October",
    "calendar.months.11": "November",
    "calendar.months.12": "December",
    "calendar.weekdays.0": "Sun",
    "calendar.weekdays.1": "Mon",
    "calendar.weekdays.2": "Tue",
    "calendar.weekdays.3": "Wed",
    "calendar.weekdays.4": "Thu",
    "calendar.weekdays.5": "Fri",
    "calendar.weekdays.6": "Sat",

    // 定价页面
    "pricing.benefit.free.status": "Basic Check-in",
    "pricing.benefit.free.journal": "Simple Journal",
    "pricing.benefit.free.video": "Basic Video Features",
    "pricing.benefit.free.ai": "5 AI Consultations Daily",
    "pricing.benefit.free.professional_test": "Professional Assessment",
    "pricing.benefit.free.professional_analysis": "Basic Data Analysis",
    "pricing.benefit.premium.all_free": "All Free Features",
    "pricing.benefit.premium.daily_push": "Daily Personalized Push",
    "pricing.benefit.premium.video": "Advanced Video Features",
    "pricing.benefit.premium.ai": "Unlimited AI Consultation",
    "pricing.benefit.premium.plan": "Personalized NoFap Plan",
    "pricing.benefit.premium.analytics": "Detailed Data Analysis",
    "pricing.benefit.premium.community": "Exclusive Community Support",

    // 反馈组件
    "feedback.title": "Feedback",
    "feedback.subtitle": "Help us improve our product and provide better service",
    "feedback.email_label": "Email Address",
    "feedback.email_placeholder": "Please enter your email address",
    "feedback.feedback_label": "Feedback Content",
    "feedback.feedback_placeholder": "Please describe your problem or suggestion in detail...",
    "feedback.rating_label": "Satisfaction Rating",
    "feedback.image_label": "Upload Screenshot",
    "feedback.image_placeholder": "Select image file",
    "feedback.image_uploading": "Uploading...",
    "feedback.image_upload_failed": "Upload failed",
    "feedback.image_remove": "Remove Image",
    "feedback.submit": "Submit Feedback",
    "feedback.submitting": "Submitting...",
    "feedback.success_title": "Submitted Successfully",
    "feedback.success_message": "Thank you for your feedback, we will handle it seriously",
    "feedback.submit_another": "Submit Another",
    //补充
    "home.join_premium_suggestion": "Join premium to unlock more exclusive features",
    "home.learn_membership_details": "Learn about membership details",

    "daily_push.unlock_title": "Unlock Today's Exclusive Content",
    "daily_push.unlock_desc": "Upgrade to premium for daily mindfulness push, meditation audio, and growth advice.",
    "daily_push.preview_quote": "Preview of today's premium quote",
    "daily_push.preview_label": "Premium Only",

    "community.premium_required_title": "Premium Community",
    "community.premium_required_desc": "This feature is for premium members only. Upgrade to join a high-quality growth community and get more support and resources.",

    "community.upgrade_to_premium": "Upgrade to Premium",
    "community.premium_feature_1": "Join exclusive growth community",
    "community.premium_feature_2": "Get expert Q&A and exclusive content",
    "community.back_to_home": "Back to Home",
    // 日记编辑器
    "journal.records": "Journal Records",
    "journal.no_records": "No records yet",

    // 每日推送
    "daily_push.title": "Daily Push",
    "daily_push.member_exclusive": "Member Exclusive",
    "daily_push.footer": "Today's Tip",

    // AI聊天组件
    "ai.welcome": "Hello! I'm your AI NoFap coach, how can I help you?",

    // 感谢页面
    "thankyou.title": "Thank You for Your Support!",
    "thankyou.subtitle": "Your feedback is very important to us",

    // 隐私政策
    "privacy.title": "Privacy Policy",

    // 首页英雄区
    "home.world_first": "The world's first <span class='highlight'>Buddhist</span> NoFap community",
    "home.buddhist": "Buddhism",
    "home.nofap_site": "NoFap Site",
    "home.awaken_slogan": "30 days to break free from addiction. Trust and persistence will change your destiny!",
    "home.traditional_method": "Combining Chinese traditions and video check-in tracking",
    // 首页测试结果区
    "home.test_overview_title": "Test Overview",
    "home.retest_button": "Retest",
    "home.test_score": "Test Score",
    "home.dependency_level": "Dependency Level",
    "home.daily_tasks": "Today's Tasks",
    "home.start_exclusive_plan": "Start Exclusive Plan",
    "home.enter_nofap_plan": "Enter NoFap Plan",
    //补充
    "plans.upgrade_to_premium_title": "Upgrade to premium and unlock all exclusive features",
"plans.premium_exclusive_features": "Premium Exclusive Features",
"plans.professional_nofap_audio": "Professional NoFap Audio Courses",
"plans.nofap_knowledge_article": "Selected NoFap Knowledge Articles",
"plans.video_checkin": "Video Check-in Growth Records",
"plans.personalized_nofap_plan": "Personalized NoFap Plan",
"plans.upgrade_now": "Upgrade Now",
"plans.maybe_later": "Maybe Later",
"plans.upgrade_to_premium": "Upgrade to premium to unlock all features",
"plans.upgrade_button": "Upgrade",
//未登录英雄区
"home.hero_line1": "Awaken discipline，Transform your life",
"home.hero_line2": "Reboot your life with Eastern healing traditions",
"home.hero_line3": "✨Build discipline with ancient practices✨",
"home.tag_video_checkin": "Video Check-in",
"home.tag_free_use": "TCM-based",
"home.tag_buddhist": "Mindful Growth",
"home.tag_gpt": "AI Companion",
"home.login_guide_title": "Log in to access full features",
"home.start_test_button": "Start Your Recovery Test",
    // 首页限时活动区
    "home.limited_event_section.limited_event": "Limited Time Event",
    "home.limited_event_section.challenge_title": "30-Day Challenge",
    "home.limited_event_section.challenge_desc": "Join our 30-day NoFap challenge with tens of thousands of users and reshape yourself with the power of persistence!",
    "home.limited_event_section.challenge_days": "Challenge Days",
    "home.limited_event_section.participants": "Participants",
    "home.limited_event_section.success_rate": "Success Rate",
    "home.limited_event_section.daily_checkin": "Daily Check-in",
    "home.limited_event_section.daily_checkin_desc": "Record your daily status, build good habits, and strengthen your confidence",
    "home.limited_event_section.community_support": "Community Support",
    "home.limited_event_section.community_support_desc": "Work together with like-minded friends and encourage each other to grow",
    "home.limited_event_section.achievement_system": "Achievement System",
    "home.limited_event_section.achievement_system_desc": "Unlock exclusive badges and record your growth journey",
    "home.limited_event_section.ai_guidance": "AI Guidance",
    "home.limited_event_section.ai_guidance_desc": "Intelligent AI assistant provides personalized suggestions and encouragement",
    "home.limited_event_section.start_challenge": "Start Challenge Now",
    "home.limited_event_section.reward_note": "Complete the challenge to receive an exclusive membership trial coupon",

    // 导航栏
    "nav.home": "Home",
    "nav.checkin": "Check-in",
    "nav.leaderboard": "Leaderboard",
    "nav.community": "Community",
    "nav.plans": "Plans",
    "nav.pricing": "Pricing",
    "nav.profile": "Profile",

    // 首页功能区
    "home.features_title": "Key Features",
    "home.features_subtitle": "Empowering your NoFap journey with science and community",
    "home.feature_daily_checkin_title": "Daily Check-in",
    "home.feature_daily_checkin_desc": "Track your daily status, build habits, and witness your growth",
    "home.feature_test_title": "Professional Assessment",
    "home.feature_test_desc": "Scientifically evaluate your dependency and get a tailored plan",
    "home.feature_plans_title": "Personalized Plan",
    "home.feature_plans_desc": "Receive a NoFap plan based on your test results",
    "home.feature_leaderboard_title": "Leaderboard",
    "home.feature_leaderboard_desc": "Compete and grow with tens of thousands of users",
    // 通用
    "common.loading": "Loading...",
    // 打卡页loading
    "checkin.loading": "Loading...",
    // 日历与打卡页
    "calendar.today": "Today",
    "calendar.makeup": "Make-up",
    "calendar.legend.today": "Today",
    "calendar.legend.success": "Success",
    "calendar.legend.failed": "Failed",
    "calendar.legend.makeup": "Make-up",
    "calendar.legend.journal": "Journal",
    "calendar.legend.video": "Video",
    "calendar.reason.future": "Future date, cannot check in",
    "calendar.rules.today": "You can only check in once today",
    "calendar.rules.recent": "Make-up available for the last 7 days",
    "calendar.rules.old": "No make-up for dates over 7 days ago",
    "calendar.rules.future": "Cannot check in for future dates",
    "checkin.title": "Daily Check-in",
    "checkin.subtitle": "Keep checking in and witness your growth",
    "checkin.currentStreak": "Current Streak",
    "checkin.currentConsecutive": "Current Consecutive Record",
    "checkin.maxStreak": "Best Streak",
    "checkin.historicalBest": "Historical Best Streak",
    "checkin.successRate": "Success Rate",
    "checkin.basedOnStreak": "Based on Streak",
    "checkin.totalDays": "Total Check-ins",
    "checkin.accumulatedRecord": "Accumulated Record",

    // AI助教功能区
    "ai.title": "AI Coach",
    "ai.premium": "Premium Only",
    "ai.unlimited": "Unlimited",
    "ai.unlimited_use": "Unlimited Use",
    "ai.today_messages": "Today's messages: {count}",
    "ai.quick_replies_title": "Quick Questions:",
    "ai.input_placeholder": "Type your question...",
    "ai.quick_reply_urges": "How to deal with strong urges?",
    "ai.quick_reply_insomnia": "How to handle insomnia during NoFap?",
    "ai.quick_reply_habits": "How to build healthy habits?",
    "ai.quick_reply_recovery": "NoFap recovery period precautions",
    "ai.quick_reply_relapse": "What to do if I relapse?",

    // 社区功能页
    "community.title": "Community",
    "community.subtitle": "Connect and grow with like-minded friends",
    "community.premium": "Premium Only",
    "community.post_placeholder": "Share your thoughts, experiences, or questions...",
    "community.post": "Post",
    "community.post_success": "Posted successfully!",
    "community.post_fail": "Failed to post, please try again",
    "community.days": "days",

    // Plans page & tasks supplement
    "task.daily_checkin": "Daily Check-in",
    "task.daily_checkin_desc": "Record today's status and build good habits",
    "task.exercise": "30-Minute Outdoor Walk",
    "task.exercise_desc": "Morning slow walk outdoors for 30 minutes to awaken yang energy",
    "task.audio_listen": "Audio Listening",
    "task.audio_desc": "Listen to meditation or course audio",
    "task.article_read": "Article Reading",
    "task.article_desc": "Read selected articles to gain knowledge",
    "task.mantra_chant": "Mantra Chanting",
    "task.mantra_desc": "Chant mantras daily to strengthen willpower",
    "task.meditation": "Meditation Practice",
    "task.meditation_desc": "Practice meditation to relax body and mind",
    "task.sleep": "Sleep Task",
    "task.sleep_desc": "Ensure enough sleep to restore energy",
    "task.exercise_instruction": "30-Minute Outdoor Walking Practice\n\nFind a quiet natural space — a park, a forest path, or by a stream. Walk slowly for 30 minutes.\nKeep your steps light and breathing deep. Don’t listen to music or scroll your phone — walk with full awareness.\nAs you walk, gently touch tree bark with your fingers, feel the sunlight on your skin, listen to birdsong. Let nature interact with you.\nYou may silently repeat mantras like “Peace,” “Gratitude,” or simply breathe in silence.\nThis is not for fitness. It is for grounding, for soaking in nature’s calm strength, for gently untangling the restless energy within.\nTip:\nTrees are living sages — touch them with reverence.\nThe breeze is a teacher — listen with a quiet heart.",
    "task.sleep_instruction": "Between 11 PM and 3 AM lies the body’s 'inner winter'—the peak time for restoring yang energy and deep healing. To prepare, put away your phone by 10 PM to avoid overstimulation. Read a book or try the Auspicious Reclining posture to settle your mind. Try to fall asleep by 10:30 PM and enter deep sleep before 11 PM, so your body can fully enter recovery mode, accumulate energy, and nourish yang energy.",
    "plans.task_instructions": "Task Instructions",
    "plans.i_understand": "I Understand",
    "plans.nofap_audio_library": "NoFap Audio Library",
    "plans.click_to_play": "Click to Play",
    "plans.professional_nofap_audio_desc": "Professional audio content to help you quit addiction scientifically and improve self-discipline.",
    // Pricing page supplement
    "pricing.title": "Pricing",
    "pricing.subtitle": "Choose the best plan for your growth",
    "pricing.free_plan": "Free Plan",
    "pricing.free_desc": "Basic features are free forever",
    "pricing.forever": "Free Forever",
    "pricing.free_trial": "Free Trial",
    "pricing.premium_plan": "Premium Plan",
    "pricing.premium_desc": "Unlock all advanced features for efficient growth",
    "pricing.recommended": "Recommended",
    "pricing.per_month": "/month",
    "pricing.join_membership": "Join Membership Now",
    "pricing.continuous_update": "Continuous feature updates",
    "pricing.payment_success": "Payment successful, welcome to premium!",
    "pricing.member_access": "Premium access enabled",
    "pricing.cancel_info": "Cancel anytime, auto-renewal",
    "pricing.contact_support": "Contact support if you have questions",
    // 英文分支
"plans.sample_task 1": "Meditation Practice",
"plans.sample_task 2": "Exercise & Fitness",
    //底部及导航栏登录组件
    "home.awaken_title": "Awaken",
    "home.about_desc": "Awaken helps you build discipline and reshape your life.",
    "footer.about": "About",
    "footer.features": "Features",
    "footer.pricing": "Pricing",
    "footer.tools": "Tools",
    "footer.test": "Addiction Test",
    "footer.checkin": "Daily Check-in",
    "home.copyright": "© 2024 Awaken. All rights reserved.",
    "nav.settings": "Settings",
    "nav.signout": "Sign out",    

    //补充英文分支
    "auth.login_title": "Sign in to Awaken",
"auth.login_description": "Choose a login method, your data will be synced securely",
    "auth.google_login": "Sign in with Google",
"auth.github_login": "Sign in with GitHub",
"auth.continue_as_guest": "Continue as Guest",
"nav.signin": "Sign In",
"common.pleaseLoginToView": "Please log in to view",
"common.pleaseLoginToUse": "Please log in to use all features",
"common.loginButton": "Log In",

"profile.features": "Features",
"profile.feature_daily_checkin": "Daily Check-in",
"profile.feature_daily_checkin_desc": "Track discipline, witness growth",
"profile.feature_plans": "Growth Plans",
"profile.feature_plans_desc": "Scientific and gradual improvement",
"profile.feature_leaderboard": "Leaderboard",
"profile.feature_leaderboard_desc": "Compete and get motivated",
"profile.feature_ai_coach": "AI Coach",
"profile.feature_ai_coach_desc": "Smart companion, instant answers",
"profile.feature_settings": "Settings",
"profile.feature_settings_desc": "Personalize your experience",

"plans.sample_tasks": "Sample Tasks",
"plans.sample_task_1": "Meditation Practice",
"plans.sample_task_1_desc": "Meditate for 10 minutes daily to build focus",
"plans.sample_button": "Start Task",
"plans.sample_task_2": "Exercise & Fitness",
"plans.sample_task_2_desc": "Exercise for 30 minutes daily to improve health",
"plans.sample_task_desc": "Task Description",

// AI 相关
"ai.remaining": "remaining",
"ai.messages": "messages",
"ai.remaining_today": "Remaining Today",

    // Plans mantra & task supplement
    "plans.mantra_practice": "Mantra Practice",
    "plans.mantra.title": "Zhunti Mantra",
    "plans.mantra.desc": "Chant daily to strengthen willpower and mindfulness",
    "plans.mantra.note": "It is recommended to chant once in the morning and once in the evening, persevere for best results.",
    "plans.chanting_method": "Chanting Method",
    "plans.find_quiet_place": "Find a quiet place and relax your body and mind",
    "plans.fold_hands": "Fold your hands and sit upright",
    "plans.chant_7_or_21_times": "Chant 7 or 21 times",
    "plans.chant_while_visualizing_master_zhunti_compassionate_light": "Visualize the compassionate light of Master Zhunti",
    "plans.pray_for_mind_purification_and_willpower_strengthening": "Pray for a pure mind and strong willpower",
    "plans.devote_yourself_to_chanting_zhunti_mantra_with_sincerity": "Devote yourself to chanting the Zhunti Mantra with sincerity,",
    "plans.it_is_recommended_to_chant_once_in_the_morning_and_once_in_the_evening_every_day": "it is recommended to chant once in the morning and once in the evening every day,",
    "plans.with_perseverance": "with perseverance, you will benefit.",
    "plans.mark_as_completed": "Mark as Completed",
    "task.meditation_instruction": "Meditation is not just a tool for inner peace, but a practice to nourish your emotions. Sit quietly for 10-20 minutes each day, close your eyes, and focus on your breath. You can silently recall people you are grateful for, warm moments, or memories of feeling loved—these will gradually dissolve inner desires and help you reconnect with life.",
    "task.auspicious_rest": "Auspicious Resting Pose (10min)",
    "task.auspicious_rest_desc": "Right-side recline before bed, restore yang, calm the mind",
    "task.auspicious_rest_instruction": "Auspicious Resting Pose (Right-Side Recline)\n\nIn a quiet, tidy space, lie down on your right side, especially before bed or meditation.\nLet your legs bend slightly. Rest your left hand gently on your left thigh, and support your head lightly with your right hand or arm. Close your eyes.\nBreathe slowly, with long and gentle exhalations. Let your awareness stay with the soft rise and fall of your belly.\nThis is the traditional resting posture of the Buddha — symbolizing peace, stability, and freedom from craving.\nAs you lie still, imagine your body floating like a lotus on calm water, untouched by desire or distraction.\nPractice for 5–10 minutes. It calms the mind, relaxes the body, and settles inner agitation — especially helpful at night.\nTip:\nKeep the body still, and the heart respectful — as if lying in the presence of sacredness.",
    "checkinModal.recordingTips": "Please keep your phone steady while recording. You can save the video after recording.",
    "checkinModal.saveVideo": "Save Video",
    "checkinModal.cameraLoading": "Camera loading...",
    "checkinModal.cameraError": "Camera initialization failed, please try again.",
    "checkinModal.cameraPermissionDenied": "Please use a device with a camera",
    "checkinModal.noCamera": "No camera?",
    "checkinModal.noCameraButton": "I don't have a camera (coming soon)",
    "checkinModal.retry": "Retry",
    "checkinModal.uploadFailed": "Upload failed",
    "checkinModal.videoSaved": "Video saved",
    "checkinModal.preview": "Preview",
    "checkinModal.startRecording": "Click the button below to start recording",
    "checkinModal.recording": "Recording",
    "checkinModal.uploading": "Uploading...",
    "checkinModal.fileSize": "File size:",
    "checkinModal.speed": "Speed:",
    "checkinModal.openCamera": "Open Camera",
    "checkinModal.startRecordingBtn": "Start Recording",
    "checkinModal.stopRecording": "Stop Recording",
    "checkinModal.statusAndLog": "Status & Log",
"checkinModal.video": "Video Check-in",
"checkinModal.checkin": "Check-in",
"checkinModal.todayStatus": "Today's Nofap Status",
"checkinModal.success": "Success",
"checkinModal.failed": "Failed",
"checkinModal.todayReflection": "Daily Recovery Log",
"checkinModal.saveCheckin": "Save Check-in",
"checkinModal.reflectionPlaceholder": "Write your reflection, summary, or today's thoughts...",
"checkinModal.videoRecord": "Video Check-in",
"checkinModal.videoUploaded": "Video Uploaded",
"checkinModal.reRecord": "Re-record"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("zh")
  
  const t = (key: string) => {
    return translations[language][key] || translations["zh"][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

export default translations 